<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>itson</groupId>
    <artifactId>SistemaCinema</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>
    <modules>
        <module>dto_negocios</module>
        <module>persistencia</module>
        <module>objetosNegocio</module>
        <module>negocios_GestorEmpleados</module>
        <module>negocios_GestorPromociones</module>
        <module>negocios_GestorVentas</module>
        <module>negocios_GestorPeliculas</module>
        <module>negocios_GestorMembresias</module>
        <module>negocios_CorreoElectronico</module>
        <module>negocios_GeneradorQR</module>
        <module>negocios_GestorBoletos</module>
        <module>negocios_GestorFunciones</module>
        <module>negocios_VenderBoleto</module>
        <module>negocios_InicioSesion</module>
        <module>presentacion_SistemaCinema</module>
        <module>negocios_InsertMasivo</module>
        <module>infraestructura_LectorQR</module>
    </modules>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
</project>