/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion.utilerias;

/**
 *
 * @author saula
 */
public class PanelPaginacion extends javax.swing.JPanel {

    private int paginaActual = 1;
    private int tamanoPagina = 6; // por defecto
    private Runnable onPaginaChange;

    /**
     * Creates new form PanelPaginacion
     */
    public PanelPaginacion() {
        initComponents();
        actualizarLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        lblNumeroPagina = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 17, 40));

        btnAtras.setBackground(new java.awt.Color(37, 99, 235));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flechaIzquierda.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(37, 99, 235));
        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flechaDerecha.png"))); // NOI18N
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        lblNumeroPagina.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblNumeroPagina.setText("Página 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras)
                .addGap(208, 208, 208)
                .addComponent(lblNumeroPagina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(btnSiguiente)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAtras))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(lblNumeroPagina)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        if (paginaActual > 1) { // no ir a páginas negativas
            paginaActual--;
            actualizarLabel();
            notificarCambio();
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        paginaActual++;
        actualizarLabel();
        notificarCambio();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    public int getPaginaActual() {
        return paginaActual;
    }

    public int getTamanoPagina() {
        return tamanoPagina;
    }

    public void setTamanoPagina(int tamanoPagina) {
        this.tamanoPagina = tamanoPagina;
    }

    public void setOnPaginaChange(Runnable listener) {
        this.onPaginaChange = listener;
    }

    private void actualizarLabel() {
        lblNumeroPagina.setText("Página " + paginaActual);
    }

    private void notificarCambio() {
        if (onPaginaChange != null) {
            onPaginaChange.run();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel lblNumeroPagina;
    // End of variables declaration//GEN-END:variables
}
