/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion.utilerias;

/**
 *
 * @author saula
 */
public class PanelBuscador extends javax.swing.JPanel {

    private final String TEXTO_DEFAULT = "BUSCAR...";
    /**
     * Creates new form buscador
     */
    public PanelBuscador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscador = new javax.swing.JTextPane();
        lblLupa = new javax.swing.JLabel();

        setBackground(new java.awt.Color(18, 31, 55));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 65, 85), 4, true));

        txtBuscador.setBackground(new java.awt.Color(18, 31, 55));
        txtBuscador.setBorder(null);
        txtBuscador.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        txtBuscador.setToolTipText("");
        txtBuscador.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtBuscador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscadorFocusLost(evt);
            }
        });

        lblLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupitaBuscador.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblLupa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLupa))
                    .addComponent(txtBuscador))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscadorFocusLost
        if(txtBuscador.getText().isEmpty()){
            txtBuscador.setText(TEXTO_DEFAULT);
        }
    }//GEN-LAST:event_txtBuscadorFocusLost

    private void txtBuscadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscadorFocusGained
        if(txtBuscador.getText().equals(TEXTO_DEFAULT)){
            txtBuscador.setText("");
        }
    }//GEN-LAST:event_txtBuscadorFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLupa;
    private javax.swing.JTextPane txtBuscador;
    // End of variables declaration//GEN-END:variables
}
