/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author saula
 */
public class formMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(formMenuPrincipal.class.getName());

    /**
     * Creates new form formMenuPrincipal
     */
    public formMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInformacionEmpleado1 = new presentacion.panelInformacionEmpleado();
        panelOpcionesMenuGerente1 = new presentacion.panelOpcionesMenuGerente();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelInformacionEmpleado1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(18, 31, 55), 1, true));
        getContentPane().add(panelInformacionEmpleado1, new java.awt.GridBagConstraints());
        getContentPane().add(panelOpcionesMenuGerente1, new java.awt.GridBagConstraints());

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private presentacion.panelInformacionEmpleado panelInformacionEmpleado1;
    private presentacion.panelOpcionesMenuGerente panelOpcionesMenuGerente1;
    // End of variables declaration//GEN-END:variables
}
