package presentacion;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Saul Isaac Apodaca Baldenegro - 00000252020
 * @author Alejandor Rodríguez Lugo - 00000251622
 */
public class FormPrincipal extends javax.swing.JFrame {

    private JPanel panelEmpleado;
    private JPanel panelOpcMenu;

    /**
     * Creates new form formMenuPrincipal
     */
    public FormPrincipal() {
        setLayout(new BorderLayout());
        setSize(1397, 788);
        panelEmpleado = new JPanel(new BorderLayout());
        add(panelEmpleado, BorderLayout.WEST);
        panelOpcMenu = new JPanel(new BorderLayout());
        add(panelOpcMenu, BorderLayout.CENTER);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicioSesionPanel2 = new presentacion.InicioSesionPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(8, 17, 40));
        getContentPane().add(inicioSesionPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getOpcMenu() {
        return panelOpcMenu;
    }

    public JPanel getPanelEmpleado() {
        return panelEmpleado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentacion.InicioSesionPanel inicioSesionPanel2;
    // End of variables declaration//GEN-END:variables
}
