package presentacion;

/**
 *
 * @author saula
 */
public class FormPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form formMenuPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInformacionEmpleado1 = new presentacion.PanelInformacionEmpleado();
        panelOpcionesMenuGerente2 = new presentacion.PanelOpcionesMenuGerente();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(8, 17, 40));
        getContentPane().add(panelInformacionEmpleado1, java.awt.BorderLayout.LINE_START);
        getContentPane().add(panelOpcionesMenuGerente2, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(8, 17, 40));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private presentacion.PanelInformacionEmpleado panelInformacionEmpleado1;
    private presentacion.PanelOpcionesMenuGerente panelOpcionesMenuGerente2;
    // End of variables declaration//GEN-END:variables
}
