/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import dto.EmpleadoDTO;
import dto.enums.TipoEmpleado;
import javax.swing.JOptionPane;
import presentacion.controles.ControlPantallas;

/**
 *
 * @author Saul Isaac Apodaca Baldenegro - 00000252020
 * @author Alejandor Rodríguez Lugo - 00000251622
 */
public class PanelOpcionesMenuEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form panelOpcionesMenu
     */
    public PanelOpcionesMenuEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVentaAlimento = new javax.swing.JButton();
        btnVentaBoleto = new javax.swing.JButton();
        btnReagendarBoleto = new javax.swing.JButton();
        btnEscaneoBoleto = new javax.swing.JButton();
        btnReembolsarBoleto = new javax.swing.JButton();
        lblVenderBoleto = new javax.swing.JLabel();
        lblReagendarBoleto = new javax.swing.JLabel();
        lblReembolsarBoleto = new javax.swing.JLabel();
        lblVenderAlimento = new javax.swing.JLabel();
        lblEscanearBoleto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 17, 40));

        btnVentaAlimento.setBackground(new java.awt.Color(18, 31, 55));
        btnVentaAlimento.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnVentaAlimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/venderAlimentos.png"))); // NOI18N
        btnVentaAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaAlimentoActionPerformed(evt);
            }
        });

        btnVentaBoleto.setBackground(new java.awt.Color(18, 31, 55));
        btnVentaBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnVentaBoleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/venderBoleto.png"))); // NOI18N
        btnVentaBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaBoletoActionPerformed(evt);
            }
        });

        btnReagendarBoleto.setBackground(new java.awt.Color(18, 31, 55));
        btnReagendarBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnReagendarBoleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reagendarBoleto.png"))); // NOI18N
        btnReagendarBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReagendarBoletoActionPerformed(evt);
            }
        });

        btnEscaneoBoleto.setBackground(new java.awt.Color(18, 31, 55));
        btnEscaneoBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnEscaneoBoleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escanearBoleto.png"))); // NOI18N
        btnEscaneoBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscaneoBoletoActionPerformed(evt);
            }
        });

        btnReembolsarBoleto.setBackground(new java.awt.Color(18, 31, 55));
        btnReembolsarBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnReembolsarBoleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReembolsarBoletos.png"))); // NOI18N
        btnReembolsarBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReembolsarBoletoActionPerformed(evt);
            }
        });

        lblVenderBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblVenderBoleto.setForeground(new java.awt.Color(255, 255, 255));
        lblVenderBoleto.setText("VENDER BOLETO");

        lblReagendarBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblReagendarBoleto.setForeground(new java.awt.Color(255, 255, 255));
        lblReagendarBoleto.setText("REAGENDAR BOLETO");

        lblReembolsarBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblReembolsarBoleto.setForeground(new java.awt.Color(255, 255, 255));
        lblReembolsarBoleto.setText("REEMBOLSAR BOLETO");

        lblVenderAlimento.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblVenderAlimento.setForeground(new java.awt.Color(255, 255, 255));
        lblVenderAlimento.setText("VENDER ALIMENTO");

        lblEscanearBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblEscanearBoleto.setForeground(new java.awt.Color(255, 255, 255));
        lblEscanearBoleto.setText("ESCANEAR BOLETO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblReembolsarBoleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(lblEscanearBoleto)
                .addGap(218, 218, 218))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lblVenderBoleto)
                        .addGap(230, 230, 230)
                        .addComponent(lblReagendarBoleto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVentaBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                            .addComponent(btnReembolsarBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEscaneoBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                            .addComponent(btnReagendarBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(btnVentaAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(lblVenderAlimento)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVentaBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReagendarBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVenderBoleto)
                    .addComponent(lblReagendarBoleto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEscaneoBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(btnReembolsarBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReembolsarBoleto)
                    .addComponent(lblEscanearBoleto))
                .addGap(18, 18, 18)
                .addComponent(btnVentaAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVenderAlimento)
                .addGap(111, 111, 111))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentaAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaAlimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentaAlimentoActionPerformed

    private void btnVentaBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaBoletoActionPerformed
        ControlPantallas.getInstance().abrirSeleccionPeliculas(this);
    }//GEN-LAST:event_btnVentaBoletoActionPerformed

    private void btnReagendarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReagendarBoletoActionPerformed
        // TODO add your handling code here:
        ControlPantallas.getInstance().abrirEscanearQR(this);
    }//GEN-LAST:event_btnReagendarBoletoActionPerformed

    private void btnEscaneoBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscaneoBoletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEscaneoBoletoActionPerformed

    private void btnReembolsarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReembolsarBoletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReembolsarBoletoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscaneoBoleto;
    private javax.swing.JButton btnReagendarBoleto;
    private javax.swing.JButton btnReembolsarBoleto;
    private javax.swing.JButton btnVentaAlimento;
    private javax.swing.JButton btnVentaBoleto;
    private javax.swing.JLabel lblEscanearBoleto;
    private javax.swing.JLabel lblReagendarBoleto;
    private javax.swing.JLabel lblReembolsarBoleto;
    private javax.swing.JLabel lblVenderAlimento;
    private javax.swing.JLabel lblVenderBoleto;
    // End of variables declaration//GEN-END:variables
}
