/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import bos.BoletoBO;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.*;
import com.google.zxing.*;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import dto.*;
import exceptions.BoletoNoExistenteException;
import exceptions.EmpleadoNoEncontradoException;
import exceptions.FuncionNoEncontradaException;
import exceptions.SucursalNoExistenteException;
import exceptions.VentaNoEncontradaException;
import interfaces.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import presentacion.controles.ControlPantallas;
import lectorQr.ILectorQR;
import lectorQr.LectorQR;
import presentacion.controles.ControlReagendarBoleto;

/**
 *
 * @author Alejandor Rodríguez Lugo - 00000251622
 */
public class PanelEscanearQR extends javax.swing.JPanel {

    private Thread hiloEscaneo;
    private Webcam webcam;
    private LectorQR lectorqr;
    private final ControlReagendarBoleto control = ControlReagendarBoleto.getInstance();

    /**
     * Creates new form EscanearQR
     */
    public PanelEscanearQR() {
        initComponents();
        this.lectorqr = new LectorQR();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEscanear = new javax.swing.JButton();
        txtBuscadorFolio = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        panelCamara = new javax.swing.JPanel();

        setBackground(new java.awt.Color(8, 17, 40));

        btnEscanear.setBackground(new java.awt.Color(37, 99, 235));
        btnEscanear.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnEscanear.setForeground(new java.awt.Color(26, 51, 83));
        btnEscanear.setText("ESCANEAR QR");
        btnEscanear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscanearActionPerformed(evt);
            }
        });

        txtBuscadorFolio.setEditable(false);
        txtBuscadorFolio.setBackground(new java.awt.Color(31, 41, 55));
        txtBuscadorFolio.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        txtBuscadorFolio.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscadorFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorFolioActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(37, 99, 235));
        btnSiguiente.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(26, 51, 83));
        btnSiguiente.setText("SIGUIENTE");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        panelCamara.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelCamaraLayout = new javax.swing.GroupLayout(panelCamara);
        panelCamara.setLayout(panelCamaraLayout);
        panelCamaraLayout.setHorizontalGroup(
            panelCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        panelCamaraLayout.setVerticalGroup(
            panelCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEscanear)
                .addGap(325, 325, 325))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(txtBuscadorFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelCamara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(panelCamara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(btnEscanear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscadorFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscanearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscanearActionPerformed
        try {
            if (webcam != null) {
                try {
                    webcam.close();
                    Thread.sleep(200);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());

                }
                webcam = null;
            }
            WebcamPanel camPanel = control.getPanelCamara();
            if (camPanel == null) {
                JOptionPane.showMessageDialog(this, "No se encontró cámara.");
                return;
            }
            webcam = camPanel.getWebcam();
            panelCamara.removeAll();
            panelCamara.setLayout(new BorderLayout());
            panelCamara.add(camPanel, BorderLayout.CENTER);
            panelCamara.revalidate();
            panelCamara.repaint();
            new Thread(() -> {
                String folio = control.escanearQR(webcam);
                if (folio != null) {
                    SwingUtilities.invokeLater(() -> txtBuscadorFolio.setText(folio));
                }
            }).start();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }//GEN-LAST:event_btnEscanearActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        if (txtBuscadorFolio.getText().isEmpty() || txtBuscadorFolio.getText() == null) {
            JOptionPane.showMessageDialog(this, "Necesitas un folio para poder avanzar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            BoletoDTO boleto = control.buscarBoletoPorId(txtBuscadorFolio.getText());
            if (boleto.getVenta().getFuncion().getFechaHora().isBefore(LocalDateTime.now().minusHours(2))) {
                JOptionPane.showMessageDialog(this, "El boleto ya no puede ser reagendado debido al margen de horas de reagenda.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            ControlPantallas.getInstance().abrirInformacionBoletoReagenda(this, boleto);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "El folio correspondiente no corresponde a un boleto del sistema.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void txtBuscadorFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorFolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorFolioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscanear;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JPanel panelCamara;
    private javax.swing.JTextField txtBuscadorFolio;
    // End of variables declaration//GEN-END:variables
}
