/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import dto.ReciboAlimentoDTO;
import presentacion.controles.ControlVentaCombo;

/**
 *
 * @author saula
 */
public class PanelInformacionRecibo extends javax.swing.JPanel {

    private ReciboAlimentoDTO recibo;
    
    /**
     * Creates new form PanelInformacionRecibo
     */
    public PanelInformacionRecibo(ReciboAlimentoDTO recibo) {
        initComponents();
        this.recibo = recibo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVisorPDF = new javax.swing.JPanel();
        btnEnviarBoleto = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(8, 17, 40));

        pnlVisorPDF.setBackground(new java.awt.Color(18, 26, 60));

        javax.swing.GroupLayout pnlVisorPDFLayout = new javax.swing.GroupLayout(pnlVisorPDF);
        pnlVisorPDF.setLayout(pnlVisorPDFLayout);
        pnlVisorPDFLayout.setHorizontalGroup(
            pnlVisorPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        pnlVisorPDFLayout.setVerticalGroup(
            pnlVisorPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );

        btnEnviarBoleto.setBackground(new java.awt.Color(37, 99, 235));
        btnEnviarBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnEnviarBoleto.setForeground(new java.awt.Color(26, 51, 83));
        btnEnviarBoleto.setText("ENVIAR BOLETO");
        btnEnviarBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarBoletoActionPerformed(evt);
            }
        });

        txtCorreo.setBackground(new java.awt.Color(31, 41, 55));
        txtCorreo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlVisorPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnEnviarBoleto)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pnlVisorPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCorreo)
                    .addComponent(btnEnviarBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarBoletoActionPerformed
        ControlVentaCombo.getInstance().mandarCorreo(recibo, txtCorreo.getText().trim());
    }//GEN-LAST:event_btnEnviarBoletoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarBoleto;
    private javax.swing.JPanel pnlVisorPDF;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
