/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import dto.ComboDTO;
import dto.SaborBebidaDTO;
import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import presentacion.controles.ControlPantallas;
import presentacion.controles.ControlVentaCombo;
import presentacion.utilerias.CardOpcion;

/**
 *
 * @author saula
 */
public class PanelPersonalizacionBebida extends javax.swing.JPanel {

    private ComboDTO combo;
    private SaborBebidaDTO bebidaActual;
    private List<CardOpcion> cardsSab = new ArrayList<>();
    private SaborBebidaDTO saborSeleccionado;

    /**
     * Creates new form PanelPersonalizacionBebida
     */
    public PanelPersonalizacionBebida(ComboDTO combo) {
        initComponents();
        this.combo = combo;
        this.bebidaActual = combo.getBebidaActual();
        lblNombreCombo.setText(combo.getNombre());
        cargarSabores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblNombreCombo = new javax.swing.JLabel();
        lblPersonalizaPalomitas = new javax.swing.JLabel();
        pnlContenedorTamanos = new javax.swing.JPanel();
        lblSeleccionaSabor = new javax.swing.JLabel();
        lblSeparador1 = new javax.swing.JLabel();
        lblSeparador2 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnConfirmarPago = new javax.swing.JButton();

        setBackground(new java.awt.Color(8, 17, 40));

        pnlFondo.setBackground(new java.awt.Color(18, 31, 55));
        pnlFondo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 65, 85), 1, true));

        lblNombreCombo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblNombreCombo.setForeground(new java.awt.Color(148, 163, 184));
        lblNombreCombo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreCombo.setText("Nombre del combo");

        lblPersonalizaPalomitas.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblPersonalizaPalomitas.setForeground(new java.awt.Color(241, 245, 249));
        lblPersonalizaPalomitas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonalizaPalomitas.setText("Personaliza la bebida");

        pnlContenedorTamanos.setBackground(new java.awt.Color(8, 17, 40));
        pnlContenedorTamanos.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout pnlContenedorTamanosLayout = new javax.swing.GroupLayout(pnlContenedorTamanos);
        pnlContenedorTamanos.setLayout(pnlContenedorTamanosLayout);
        pnlContenedorTamanosLayout.setHorizontalGroup(
            pnlContenedorTamanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlContenedorTamanosLayout.setVerticalGroup(
            pnlContenedorTamanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        lblSeleccionaSabor.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblSeleccionaSabor.setForeground(new java.awt.Color(241, 245, 249));
        lblSeleccionaSabor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeleccionaSabor.setText("Selecciona el sabor");

        lblSeparador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeparador1.setText("_______________________________________________________________________________________________________________________________________________________________________________________");

        lblSeparador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeparador2.setText("_______________________________________________________________________________________________________________________________________________________________________________________");

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContenedorTamanos, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                    .addComponent(lblSeparador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPersonalizaPalomitas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSeparador2, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                    .addComponent(lblSeleccionaSabor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreCombo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPersonalizaPalomitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeparador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeleccionaSabor)
                .addGap(9, 9, 9)
                .addComponent(pnlContenedorTamanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeparador2)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        btnVolver.setBackground(new java.awt.Color(37, 99, 235));
        btnVolver.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(26, 51, 83));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnConfirmarPago.setBackground(new java.awt.Color(37, 99, 235));
        btnConfirmarPago.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnConfirmarPago.setForeground(new java.awt.Color(26, 51, 83));
        btnConfirmarPago.setText("SIGUIENTE");
        btnConfirmarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmarPago))
                    .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
         ControlPantallas.getInstance().abrirPersonalizacionPalomitas(combo);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnConfirmarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPagoActionPerformed
        if (saborSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un sabor para la bebida.");
            return;
        }

        // Guardar el sabor elegido en la bebida actual
        bebidaActual.setId(saborSeleccionado.getId());
        bebidaActual.setNombre(saborSeleccionado.getNombre());
        bebidaActual.setPrecioExtra(saborSeleccionado.getPrecioExtra());
        bebidaActual.setRutaImagen(saborSeleccionado.getRutaImagen());

        // Si hay más bebidas por personalizar
        if (combo.hayMasBebidas()) {
            combo.avanzarBebida();
            ControlPantallas.getInstance().abrirPersonalizacionBebidas(combo);
        } else {
            if (combo.getDulceDTO() == null){
                ControlPantallas.getInstance().abrirInformacionPagoCombo(combo);
            }
            ControlPantallas.getInstance().abrirPersonalizacionDulce(combo);
        }
    }//GEN-LAST:event_btnConfirmarPagoActionPerformed

    private void cargarSabores() {
        List<SaborBebidaDTO> listaSabores
                = ControlVentaCombo.getInstance().obtenerSaboresBebidas();

        pnlContenedorTamanos.setLayout(new FlowLayout(FlowLayout.LEFT, 20, 20));

        for (SaborBebidaDTO sab : listaSabores) {

            CardOpcion card = new CardOpcion(
                    sab.getNombre(),
                    sab.getPrecioExtra(),
                    sab.getRutaImagen()
            );

            card.setOnClick(() -> {
                saborSeleccionado = sab;
                cardsSab.forEach(c -> c.deseleccionar());
                card.seleccionar();
            });

            cardsSab.add(card);
            pnlContenedorTamanos.add(card);
        }

        pnlContenedorTamanos.revalidate();
        pnlContenedorTamanos.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarPago;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblNombreCombo;
    private javax.swing.JLabel lblPersonalizaPalomitas;
    private javax.swing.JLabel lblSeleccionaSabor;
    private javax.swing.JLabel lblSeparador1;
    private javax.swing.JLabel lblSeparador2;
    private javax.swing.JPanel pnlContenedorTamanos;
    private javax.swing.JPanel pnlFondo;
    // End of variables declaration//GEN-END:variables
}
