package presentacion;

import bos.*;
import daos.FuncionDAO;
import dto.BoletoDTO;
import dto.*;
import dto.enums.EstadoAsiento;
import dto.enums.FormaPago;
import exceptions.EmpleadoNoEncontradoException;
import exceptions.FuncionNoEncontradaException;
import exceptions.PromocionNoExistenteException;
import exceptions.SucursalNoExistenteException;
import exceptions.VentaNoEncontradaException;
import itson.negocios_generadorqr.exceptions.QRGeneradorException;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import presentacion.controles.*;
import presentacion.controles.ControlPantallas;
import presentacion.utilerias.GestorSesion;

/**
 *
 * @author saula
 */
public class PanelInformacionReagenda extends javax.swing.JPanel {

    private BoletoDTO boleto;
    private FuncionDTO funcion;
    private List<AsientoDTO> asientos;
    private final BoletoBO instance = BoletoBO.getInstancia();
    private final PeliculaBO instance1 = PeliculaBO.getInstancia();
    private final ControlReagendarBoleto control = ControlReagendarBoleto.getInstance();
    private ArrayList<AsientoDTO> asientosOriginales;
    private VentaDTO ventaOriginal;

    /**
     * Creates new form PanelInformacionBoleto
     */
    public PanelInformacionReagenda(BoletoDTO boleto, FuncionDTO funcion, List<AsientoDTO> asientos) {
        this.boleto = boleto;
        this.funcion = funcion;
        this.asientos = asientos;
        initComponents();
        cargarBoleto();
        cargarBoletoNuevo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVisorPDF = new javax.swing.JPanel();
        lblSala = new javax.swing.JLabel();
        lblAsientos = new javax.swing.JLabel();
        lblFuncion = new javax.swing.JLabel();
        lblAntiguo = new javax.swing.JLabel();
        lblNuevo = new javax.swing.JLabel();
        lblFuncionNuevo = new javax.swing.JLabel();
        lblSalaNuevo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblFechaNuevo = new javax.swing.JLabel();
        lblAsientoNuevos = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(8, 17, 40));

        pnlVisorPDF.setBackground(new java.awt.Color(18, 26, 60));

        lblSala.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblSala.setForeground(new java.awt.Color(255, 255, 255));
        lblSala.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSala.setText("jLabel1");

        lblAsientos.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblAsientos.setForeground(new java.awt.Color(255, 255, 255));
        lblAsientos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsientos.setText("jLabel1");

        lblFuncion.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblFuncion.setForeground(new java.awt.Color(255, 255, 255));
        lblFuncion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFuncion.setText("jLabel1");

        lblAntiguo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblAntiguo.setForeground(new java.awt.Color(255, 255, 255));
        lblAntiguo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAntiguo.setText("BOLETO ORIGINAL");

        lblNuevo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblNuevo.setForeground(new java.awt.Color(255, 255, 255));
        lblNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNuevo.setText("BOLETO NUEVO");

        lblFuncionNuevo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblFuncionNuevo.setForeground(new java.awt.Color(255, 255, 255));
        lblFuncionNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFuncionNuevo.setText("jLabel1");

        lblSalaNuevo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblSalaNuevo.setForeground(new java.awt.Color(255, 255, 255));
        lblSalaNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalaNuevo.setText("jLabel1");

        lblFecha.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("jLabel1");

        lblFechaNuevo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblFechaNuevo.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaNuevo.setText("jLabel1");

        lblAsientoNuevos.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblAsientoNuevos.setForeground(new java.awt.Color(255, 255, 255));
        lblAsientoNuevos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsientoNuevos.setText("jLabel1");

        javax.swing.GroupLayout pnlVisorPDFLayout = new javax.swing.GroupLayout(pnlVisorPDF);
        pnlVisorPDF.setLayout(pnlVisorPDFLayout);
        pnlVisorPDFLayout.setHorizontalGroup(
            pnlVisorPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisorPDFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVisorPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVisorPDFLayout.createSequentialGroup()
                        .addComponent(lblAntiguo, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lblNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlVisorPDFLayout.createSequentialGroup()
                        .addGroup(pnlVisorPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVisorPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblSala, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                                .addComponent(lblFuncion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlVisorPDFLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlVisorPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSalaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFuncionNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(pnlVisorPDFLayout.createSequentialGroup()
                        .addComponent(lblAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAsientoNuevos, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlVisorPDFLayout.setVerticalGroup(
            pnlVisorPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisorPDFLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlVisorPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAntiguo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlVisorPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFuncionNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlVisorPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSala, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlVisorPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlVisorPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsientoNuevos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        btnConfirmar.setBackground(new java.awt.Color(37, 99, 235));
        btnConfirmar.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(26, 51, 83));
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(37, 99, 235));
        btnVolver.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(26, 51, 83));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(521, 521, 521)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(pnlVisorPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(pnlVisorPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        VentaDTO venta = boleto.getVenta();
        this.asientosOriginales = new ArrayList<>(boleto.getVenta().getAsientos());
        this.ventaOriginal = venta;
        VentaDTO ventaAntigua = new VentaDTO();
        ventaAntigua.setId(venta.getId());
        ventaAntigua.setEmpleado(venta.getEmpleado());
        ventaAntigua.setFecha(venta.getFecha());
        ventaAntigua.setFuncion(venta.getFuncion());
        VentaDTO ventaNueva = venta;
        List<AsientoDTO> asientosAntiguos = new ArrayList<>(asientosOriginales);
        List<AsientoDTO> asientosNuevos = asientos;
        venta.setEmpleado(GestorSesion.getUsuario());
        venta.setFecha(LocalDate.now());
        try {
            venta.setFuncion(funcion);
            venta.setAsientos(asientosNuevos);
            control.reagendarBoleto(ventaAntigua, ventaNueva, asientosAntiguos, asientosNuevos);
            JOptionPane.showMessageDialog(this, "Se logro reagendar el boleto.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            ControlPantallas.getInstance().abrirInformacionBoleto(pnlVisorPDF, boleto);
        } catch (Exception ex) {
            Logger.getLogger(PanelInformacionReagenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ControlPantallas.getInstance().abrirSeleccionAsientosReagenda(this, funcion, boleto);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cargarBoleto() {
        lblFuncion.setText("Película: " + boleto.getVenta().getFuncion().getPelicula().getTitulo());
        lblSala.setText("Sala: " + boleto.getVenta().getFuncion().getSala().getNombre());
        LocalDateTime fechaHora = boleto.getVenta().getFuncion().getFechaHora();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        String fechaFormateada = fechaHora.format(formato);
        lblFecha.setText(fechaFormateada);
        lblAsientos.setText("Asientos: " + boleto.getVenta().getAsientos().toString());
    }

    private void cargarBoletoNuevo() {
        lblFuncionNuevo.setText("Película: " + funcion.getPelicula().getTitulo());
        lblSalaNuevo.setText("Sala: " + funcion.getSala().getNombre());
        LocalDateTime fechaHora = funcion.getFechaHora();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        String fechaFormateada = fechaHora.format(formato);
        lblFechaNuevo.setText(fechaFormateada);
        lblAsientoNuevos.setText("Asientos: " + asientos.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblAntiguo;
    private javax.swing.JLabel lblAsientoNuevos;
    private javax.swing.JLabel lblAsientos;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaNuevo;
    private javax.swing.JLabel lblFuncion;
    private javax.swing.JLabel lblFuncionNuevo;
    private javax.swing.JLabel lblNuevo;
    private javax.swing.JLabel lblSala;
    private javax.swing.JLabel lblSalaNuevo;
    private javax.swing.JPanel pnlVisorPDF;
    // End of variables declaration//GEN-END:variables
}
