/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import presentacion.controles.ControlPantallas;
import dto.AsientoDTO;
import dto.BoletoDTO;
import dto.FuncionDTO;
import dto.SalaDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.SwingConstants;
import presentacion.utilerias.PintorAsientos;

/**
 *
 * @author Alejandor Rodríguez Lugo - 00000251622
 */
public class PanelSeleccionAsientosReagenda extends javax.swing.JPanel {

    private FuncionDTO funcion;
    private BoletoDTO boleto;
    private JToggleButton[][] botones;

    /**
     * Creates new form PanelSeleccionAsientos
     *
     * @param funcion
     */
    public PanelSeleccionAsientosReagenda(FuncionDTO funcion, BoletoDTO boleto) {
        this.funcion = funcion;
        this.boleto = boleto;
        initComponents();
        configurarCantidad();
        SalaDTO sala = funcion.getSala();
        configurarMapaAsientos(sala);
        botones = new JToggleButton[sala.getFilas()][sala.getColumnas()];
        inicializarAsientos();
        configurarInformacionFuncion();
        cargarNumerosFilas(funcion.getSala().getFilas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFuncion = new javax.swing.JPanel();
        lblNombreSalaFuncion = new javax.swing.JLabel();
        lblHoraFuncion = new javax.swing.JLabel();
        lblTipoSalaFuncion = new javax.swing.JLabel();
        lblNombrePelicula = new javax.swing.JLabel();
        lblAsientos = new javax.swing.JLabel();
        pnlContenedor = new javax.swing.JPanel();
        pnlPantalla = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlMapaAsientos = new javax.swing.JPanel();
        pnlNumerosFilas = new javax.swing.JPanel();
        pnlSimbología = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(8, 17, 40));

        pnlFuncion.setBackground(new java.awt.Color(18, 31, 55));
        pnlFuncion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 65, 85), 3, true));

        lblNombreSalaFuncion.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblNombreSalaFuncion.setText("SALA 1");

        lblHoraFuncion.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblHoraFuncion.setText("00:00");

        lblTipoSalaFuncion.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblTipoSalaFuncion.setForeground(new java.awt.Color(148, 163, 184));
        lblTipoSalaFuncion.setText("SALA TRADICIONAL");

        lblNombrePelicula.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblNombrePelicula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombrePelicula.setText("NOMBRE DE LA PELÍCULA");

        lblAsientos.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblAsientos.setForeground(new java.awt.Color(255, 255, 255));
        lblAsientos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAsientos.setText("JLabel1");

        javax.swing.GroupLayout pnlFuncionLayout = new javax.swing.GroupLayout(pnlFuncion);
        pnlFuncion.setLayout(pnlFuncionLayout);
        pnlFuncionLayout.setHorizontalGroup(
            pnlFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFuncionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFuncionLayout.createSequentialGroup()
                        .addComponent(lblHoraFuncion)
                        .addGap(108, 108, 108)
                        .addComponent(lblAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
                    .addGroup(pnlFuncionLayout.createSequentialGroup()
                        .addComponent(lblNombreSalaFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNombrePelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipoSalaFuncion)
                .addContainerGap())
        );
        pnlFuncionLayout.setVerticalGroup(
            pnlFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFuncionLayout.createSequentialGroup()
                .addGroup(pnlFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreSalaFuncion)
                    .addGroup(pnlFuncionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoSalaFuncion)
                            .addComponent(lblNombrePelicula))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoraFuncion)
                    .addComponent(lblAsientos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlContenedor.setBackground(new java.awt.Color(18, 26, 60));

        pnlPantalla.setBackground(new java.awt.Color(22, 25, 26));
        pnlPantalla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 40, 76), 1, true));
        pnlPantalla.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PANTALLA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlPantalla.add(jLabel1, java.awt.BorderLayout.CENTER);

        pnlMapaAsientos.setBackground(new java.awt.Color(18, 26, 60));
        pnlMapaAsientos.setMaximumSize(null);

        javax.swing.GroupLayout pnlMapaAsientosLayout = new javax.swing.GroupLayout(pnlMapaAsientos);
        pnlMapaAsientos.setLayout(pnlMapaAsientosLayout);
        pnlMapaAsientosLayout.setHorizontalGroup(
            pnlMapaAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlMapaAsientosLayout.setVerticalGroup(
            pnlMapaAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        pnlNumerosFilas.setBackground(new java.awt.Color(18, 26, 60));

        javax.swing.GroupLayout pnlNumerosFilasLayout = new javax.swing.GroupLayout(pnlNumerosFilas);
        pnlNumerosFilas.setLayout(pnlNumerosFilasLayout);
        pnlNumerosFilasLayout.setHorizontalGroup(
            pnlNumerosFilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlNumerosFilasLayout.setVerticalGroup(
            pnlNumerosFilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlNumerosFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlMapaAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlNumerosFilas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMapaAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        pnlSimbología.setBackground(new java.awt.Color(18, 26, 60));
        pnlSimbología.setLayout(new java.awt.GridLayout(3, 1, 1, 3));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asientoDisponible.png"))); // NOI18N
        jLabel2.setText("DISPONIBLE");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlSimbología.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asientoSeleccionado.png"))); // NOI18N
        jLabel3.setText("SELECCIONADO");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlSimbología.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asientoOcupado.png"))); // NOI18N
        jLabel4.setText("OCUPADO");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pnlSimbología.add(jLabel4);

        btnSiguiente.setBackground(new java.awt.Color(37, 99, 235));
        btnSiguiente.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(26, 51, 83));
        btnSiguiente.setText("SIGUIENTE");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(37, 99, 235));
        btnVolver.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(26, 51, 83));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFuncion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(pnlSimbología, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSimbología, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ControlPantallas.getInstance().abrirSeleccionFuncionReagenda(this, funcion.getPelicula(), boleto);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        List<AsientoDTO> asientosSeleccionados = obtenerAsientosSeleccionados();
        if (asientosSeleccionados.size() != boleto.getVenta().getAsientos().size()) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar la misma cantidad de asientos comprados originalmente para continuar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ControlPantallas.getInstance().abrirInformacionReagenda(this, boleto, funcion, asientosSeleccionados);
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void configurarCantidad() {
        lblAsientos.setText("Cantidad de asientos: " + boleto.getVenta().getAsientos().size());
    }

    private void configurarMapaAsientos(SalaDTO sala) {
        int tam = 50;
        int margen = 5;
        pnlMapaAsientos.removeAll();
        pnlMapaAsientos.setLayout(new GridLayout(sala.getFilas(), sala.getColumnas(), margen, margen));
        int anchoTotal = sala.getColumnas() * (tam + margen);
        int altoTotal = sala.getFilas() * (tam + margen);
        pnlMapaAsientos.setPreferredSize(new Dimension(anchoTotal, altoTotal));
        pnlMapaAsientos.setMaximumSize(new Dimension(anchoTotal, altoTotal));
        pnlMapaAsientos.setMinimumSize(new Dimension(anchoTotal, altoTotal));
        pnlMapaAsientos.revalidate();
        pnlMapaAsientos.repaint();
    }

    private void configurarInformacionFuncion() {
        limpiarEtiquetas();
        aplicarInfoEtiqueta(lblNombrePelicula, funcion.getPelicula().getTitulo());
        aplicarInfoEtiqueta(lblNombreSalaFuncion, funcion.getSala().getNombre());
        LocalDateTime fechaHora = funcion.getFechaHora();
        String hora = fechaHora.toLocalTime().format(DateTimeFormatter.ofPattern("hh:mm a"));
        aplicarInfoEtiqueta(lblHoraFuncion, hora);
        aplicarInfoEtiqueta(lblTipoSalaFuncion, funcion.getTipoSala());
        lblTipoSalaFuncion.setForeground(new Color(148, 163, 184));
    }

    private void aplicarInfoEtiqueta(JLabel etiqueta, String texto) {
        etiqueta.setText(texto);
        etiqueta.setForeground(new Color(205, 205, 205));
    }

    private void limpiarEtiquetas() {
        lblNombrePelicula.setText("");
        lblNombreSalaFuncion.setText("");
        lblTipoSalaFuncion.setText("");
        lblHoraFuncion.setText("");
    }

    private void inicializarAsientos() {
        for (AsientoDTO asiento : funcion.getAsientos()) {
            int fila = asiento.getFila();
            int columna = asiento.getColumna();
            JToggleButton btn = crearBotonAsiento(asiento);
            botones[fila][columna - 1] = btn;
            pnlMapaAsientos.add(btn);
        }
    }

    private JToggleButton crearBotonAsiento(AsientoDTO asiento) {
        JToggleButton btn = new JToggleButton("");
        btn.setPreferredSize(new Dimension(50, 50));
        btn.setSize(new Dimension(50, 50));
        btn.setText(String.valueOf(asiento.getColumna()));
        btn.setForeground(Color.WHITE);
        btn.setHorizontalTextPosition(SwingConstants.CENTER);
        PintorAsientos.aplicarEstilo(btn, asiento.getEstado());
        configurarEventoSeleccion(btn);
        return btn;
    }

    private void configurarEventoSeleccion(JToggleButton btn) {
        btn.addActionListener(e -> {
            if (btn.isSelected()) {
                PintorAsientos.aplicarSeleccion(btn, true);
            } else {
                PintorAsientos.aplicarSeleccion(btn, false);
            }
        });
    }

    private List<AsientoDTO> obtenerAsientosSeleccionados() {
        return funcion.getAsientos().stream()
                .filter(a -> {
                    JToggleButton b = botones[a.getFila()][a.getColumna() - 1];
                    return b.isSelected();
                }).toList();
    }

    private void cargarNumerosFilas(int cantidadFilas) {
        pnlNumerosFilas.removeAll();
        pnlNumerosFilas.setLayout(new GridLayout(cantidadFilas, 1, 0, 10));
        char letra = (char) ('A');
        for (int i = 1; i <= cantidadFilas; i++) {
            JLabel lblNumero = new JLabel(String.valueOf(letra), SwingConstants.CENTER);
            lblNumero.setFont(new Font("Comic Sans MS", Font.BOLD, 18));
            lblNumero.setForeground(Color.WHITE);
            lblNumero.setHorizontalAlignment(SwingConstants.CENTER);
            pnlNumerosFilas.add(lblNumero);
            letra = (char) ('A' + i);
        }
        pnlNumerosFilas.revalidate();
        pnlNumerosFilas.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAsientos;
    private javax.swing.JLabel lblHoraFuncion;
    private javax.swing.JLabel lblNombrePelicula;
    private javax.swing.JLabel lblNombreSalaFuncion;
    private javax.swing.JLabel lblTipoSalaFuncion;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlFuncion;
    private javax.swing.JPanel pnlMapaAsientos;
    private javax.swing.JPanel pnlNumerosFilas;
    private javax.swing.JPanel pnlPantalla;
    private javax.swing.JPanel pnlSimbología;
    // End of variables declaration//GEN-END:variables
}
