package presentacion;

import dto.BoletoDTO;
import dto.PeliculaDTO;
import dto.VentaDTO;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.image.BufferedImage;
import java.time.format.DateTimeFormatter;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;
import presentacion.controles.ControlPantallas;
import presentacion.controles.ControlReagendarBoleto;

/**
 *
 * @author Alejandor Rodríguez Lugo - 00000251622
 */
public class PanelFechasReporte extends javax.swing.JPanel {

    private PeliculaDTO pelicula;

    /**
     * Creates new form PanelInformacionBoleto
     *
     * @param pelicula
     */
    public PanelFechasReporte(PeliculaDTO pelicula) {
        this.pelicula = pelicula;
        initComponents();
        configurarRadioButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        btnContinuar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblFechaHasta = new javax.swing.JLabel();
        jrSi = new javax.swing.JRadioButton();
        jrNo = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        lblFechaReportes1 = new javax.swing.JLabel();
        lblFechaDesde = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 17, 40));

        btnContinuar.setBackground(new java.awt.Color(37, 99, 235));
        btnContinuar.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(26, 51, 83));
        btnContinuar.setText("CONTINUAR");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(37, 99, 235));
        btnVolver.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(26, 51, 83));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblFechaHasta.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblFechaHasta.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaHasta.setText("FECHA HASTA:");

        jrSi.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jrSi.setForeground(new java.awt.Color(255, 255, 255));
        jrSi.setText("SI");

        jrNo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jrNo.setForeground(new java.awt.Color(255, 255, 255));
        jrNo.setSelected(true);
        jrNo.setText("NO");

        lblFechaReportes1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblFechaReportes1.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaReportes1.setText("¿DESEAS SELECCIONAR UN RANGO DE FECHAS PARA TU REPORTE?");

        lblFechaDesde.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblFechaDesde.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaDesde.setText("FECHA DESDE:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jrSi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jrNo)
                        .addGap(264, 264, 264))))
            .addGroup(layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(lblFechaReportes1, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
                    .addGap(16, 16, 16)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrSi)
                    .addComponent(jrNo))
                .addGap(35, 35, 35)
                .addComponent(lblFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(138, 138, 138)
                    .addComponent(lblFechaReportes1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(466, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        if (jrNo.isSelected()) {
            ControlPantallas.getInstance().abrirReportePelicula(this, pelicula, null, null);
        } else {
            if (jDateChooser1.getDate() != null && jDateChooser2.getDate() != null) {
                if (jDateChooser1.getDate().after(jDateChooser2.getDate())) {
                    JOptionPane.showMessageDialog(this, "La fecha 'desde' tiene que ser menor o igual a la fecha 'hasta'.", "Error", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            Date fechaInicioDate = jDateChooser1.getDate();
            Date fechaFinDate = jDateChooser2.getDate();
            LocalDate fechaInicio = null;
            LocalDate fechaFin = null;
            if (fechaInicioDate != null) {
                fechaInicio = fechaInicioDate.toInstant()
                        .atZone(ZoneId.systemDefault())
                        .toLocalDate();
            }
            if (fechaFinDate != null) {
                fechaFin = fechaFinDate.toInstant()
                        .atZone(ZoneId.systemDefault())
                        .toLocalDate();
            }
            ControlPantallas.getInstance().abrirReportePelicula(this, pelicula, fechaInicio, fechaFin);
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ControlPantallas.getInstance().abrirSeleccionPeliculasReporte(this);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void configurarRadioButtons() {
        jDateChooser1.setEnabled(false);
        jDateChooser2.setEnabled(false);
        jrSi.addActionListener(e -> {
            jrSi.setSelected(true);
            jrNo.setSelected(false);
            jDateChooser1.setEnabled(true);
            jDateChooser2.setEnabled(true);
        });
        jrNo.addActionListener(e -> {
            jrNo.setSelected(true);
            jrSi.setSelected(false);
            jDateChooser1.setEnabled(false);
            jDateChooser2.setEnabled(false);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnVolver;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrNo;
    private javax.swing.JRadioButton jrSi;
    private javax.swing.JLabel lblFechaDesde;
    private javax.swing.JLabel lblFechaHasta;
    private javax.swing.JLabel lblFechaReportes1;
    // End of variables declaration//GEN-END:variables
}
