/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import dto.ComboDTO;
import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import presentacion.controles.ControlPantallas;

/**
 *
 * @author saula
 */
public class PanelDetalleCombo extends javax.swing.JPanel {

    private ComboDTO combo;
    
    /**
     * Creates new form PanelDetalleCombo
     * @param combo
     */
    public PanelDetalleCombo(ComboDTO combo) {
        initComponents();
        this.combo = combo;
        configurarImagen();
        configurarInfoCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDetalleCombo1 = new javax.swing.JPanel();
        lblPersonalizarBebidastxt = new javax.swing.JLabel();
        lblFlecha = new javax.swing.JLabel();
        lblBebidastxt = new javax.swing.JLabel();
        pnlPersonalizarPalomitas = new javax.swing.JPanel();
        lblPersonalizarPalomitasTxt1 = new javax.swing.JLabel();
        lblFlecha1 = new javax.swing.JLabel();
        lblPalomitatxt1 = new javax.swing.JLabel();
        pnlDetalleCombo2 = new javax.swing.JPanel();
        lblPersonalizacionExtrastxt = new javax.swing.JLabel();
        lblFlecha2 = new javax.swing.JLabel();
        lblExtrastxt = new javax.swing.JLabel();
        pnlImagenCombo = new javax.swing.JPanel();
        lblImagenCombo = new javax.swing.JLabel();
        lblNombreCombo = new javax.swing.JLabel();
        lblPrecioCombo = new javax.swing.JLabel();
        lblDescripcionCombo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        setBackground(new java.awt.Color(8, 17, 40));

        pnlDetalleCombo1.setBackground(new java.awt.Color(18, 31, 55));
        pnlDetalleCombo1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 65, 85), 3, true));

        lblPersonalizarBebidastxt.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblPersonalizarBebidastxt.setText("Personalizar Bebidas");

        lblFlecha.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblFlecha.setText(">");

        lblBebidastxt.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblBebidastxt.setForeground(new java.awt.Color(148, 163, 184));
        lblBebidastxt.setText("Bebidas");

        javax.swing.GroupLayout pnlDetalleCombo1Layout = new javax.swing.GroupLayout(pnlDetalleCombo1);
        pnlDetalleCombo1.setLayout(pnlDetalleCombo1Layout);
        pnlDetalleCombo1Layout.setHorizontalGroup(
            pnlDetalleCombo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleCombo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBebidastxt)
                .addGap(260, 260, 260)
                .addComponent(lblPersonalizarBebidastxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                .addComponent(lblFlecha)
                .addGap(18, 18, 18))
        );
        pnlDetalleCombo1Layout.setVerticalGroup(
            pnlDetalleCombo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleCombo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetalleCombo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalleCombo1Layout.createSequentialGroup()
                        .addComponent(lblBebidastxt)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetalleCombo1Layout.createSequentialGroup()
                        .addGroup(pnlDetalleCombo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPersonalizarBebidastxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFlecha, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        pnlPersonalizarPalomitas.setBackground(new java.awt.Color(18, 31, 55));
        pnlPersonalizarPalomitas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 65, 85), 3, true));

        lblPersonalizarPalomitasTxt1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblPersonalizarPalomitasTxt1.setText("Personalizar Palomitas");

        lblFlecha1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblFlecha1.setText(">");

        lblPalomitatxt1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblPalomitatxt1.setForeground(new java.awt.Color(148, 163, 184));
        lblPalomitatxt1.setText("Palomitas");

        javax.swing.GroupLayout pnlPersonalizarPalomitasLayout = new javax.swing.GroupLayout(pnlPersonalizarPalomitas);
        pnlPersonalizarPalomitas.setLayout(pnlPersonalizarPalomitasLayout);
        pnlPersonalizarPalomitasLayout.setHorizontalGroup(
            pnlPersonalizarPalomitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalizarPalomitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPalomitatxt1)
                .addGap(228, 228, 228)
                .addComponent(lblPersonalizarPalomitasTxt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFlecha1)
                .addGap(18, 18, 18))
        );
        pnlPersonalizarPalomitasLayout.setVerticalGroup(
            pnlPersonalizarPalomitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalizarPalomitasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPersonalizarPalomitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPersonalizarPalomitasLayout.createSequentialGroup()
                        .addComponent(lblPalomitatxt1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPersonalizarPalomitasLayout.createSequentialGroup()
                        .addGroup(pnlPersonalizarPalomitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPersonalizarPalomitasTxt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFlecha1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        pnlDetalleCombo2.setBackground(new java.awt.Color(18, 31, 55));
        pnlDetalleCombo2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 65, 85), 3, true));

        lblPersonalizacionExtrastxt.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblPersonalizacionExtrastxt.setText("Personalizar Extras");

        lblFlecha2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblFlecha2.setText(">");

        lblExtrastxt.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblExtrastxt.setForeground(new java.awt.Color(148, 163, 184));
        lblExtrastxt.setText("Extras");

        javax.swing.GroupLayout pnlDetalleCombo2Layout = new javax.swing.GroupLayout(pnlDetalleCombo2);
        pnlDetalleCombo2.setLayout(pnlDetalleCombo2Layout);
        pnlDetalleCombo2Layout.setHorizontalGroup(
            pnlDetalleCombo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleCombo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExtrastxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPersonalizacionExtrastxt)
                .addGap(261, 261, 261)
                .addComponent(lblFlecha2)
                .addGap(18, 18, 18))
        );
        pnlDetalleCombo2Layout.setVerticalGroup(
            pnlDetalleCombo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleCombo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetalleCombo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalleCombo2Layout.createSequentialGroup()
                        .addComponent(lblExtrastxt)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetalleCombo2Layout.createSequentialGroup()
                        .addGroup(pnlDetalleCombo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPersonalizacionExtrastxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFlecha2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        pnlImagenCombo.setLayout(new java.awt.BorderLayout());

        lblImagenCombo.setText("jLabel1");
        pnlImagenCombo.add(lblImagenCombo, java.awt.BorderLayout.CENTER);

        lblNombreCombo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblNombreCombo.setText("NOMBRE DEL COMBO");

        lblPrecioCombo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblPrecioCombo.setText("$00.00");

        lblDescripcionCombo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblDescripcionCombo.setForeground(new java.awt.Color(148, 163, 184));
        lblDescripcionCombo.setText("Descripcion del combo");

        btnVolver.setBackground(new java.awt.Color(37, 99, 235));
        btnVolver.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(26, 51, 83));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(37, 99, 235));
        btnSiguiente.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(26, 51, 83));
        btnSiguiente.setText("SIGUIENTE");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlImagenCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreCombo)
                            .addComponent(lblPrecioCombo)
                            .addComponent(lblDescripcionCombo)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pnlPersonalizarPalomitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlDetalleCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlDetalleCombo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblNombreCombo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPrecioCombo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescripcionCombo)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlImagenCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(pnlPersonalizarPalomitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDetalleCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDetalleCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ControlPantallas.getInstance().abrirPersonalizacionPalomitas(combo);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void configurarImagen() {
        lblImagenCombo.setText("");
        lblImagenCombo.setHorizontalAlignment(SwingConstants.CENTER);

        URL url = getClass().getResource("/ImagenesCombos/" + this.combo.getRutaImagen());
        if (url != null) {
            ImageIcon icon = new ImageIcon(url);
            Image img = icon.getImage().getScaledInstance(320, 320, Image.SCALE_SMOOTH);
            lblImagenCombo.setIcon(new ImageIcon(img));
        } else {
            lblImagenCombo.setText("🍔");
            lblImagenCombo.setForeground(new Color(205, 205, 205));
        }
    }
    
   
    private void configurarInfoCombo() {
        lblNombreCombo.setText(this.combo.getNombre().toUpperCase());
        lblNombreCombo.setForeground(new Color(204, 204, 204));
        lblDescripcionCombo.setText(this.combo.getDescripcion());
        lblDescripcionCombo.setForeground(new Color(148, 163, 184));
        lblPrecioCombo.setText(String.format("$%.2f", this.combo.getPrecio()));
        lblPrecioCombo.setForeground(new Color(204, 204, 204));

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblBebidastxt;
    private javax.swing.JLabel lblDescripcionCombo;
    private javax.swing.JLabel lblExtrastxt;
    private javax.swing.JLabel lblFlecha;
    private javax.swing.JLabel lblFlecha1;
    private javax.swing.JLabel lblFlecha2;
    private javax.swing.JLabel lblImagenCombo;
    private javax.swing.JLabel lblNombreCombo;
    private javax.swing.JLabel lblPalomitatxt1;
    private javax.swing.JLabel lblPersonalizacionExtrastxt;
    private javax.swing.JLabel lblPersonalizarBebidastxt;
    private javax.swing.JLabel lblPersonalizarPalomitasTxt1;
    private javax.swing.JLabel lblPrecioCombo;
    private javax.swing.JPanel pnlDetalleCombo1;
    private javax.swing.JPanel pnlDetalleCombo2;
    private javax.swing.JPanel pnlImagenCombo;
    private javax.swing.JPanel pnlPersonalizarPalomitas;
    // End of variables declaration//GEN-END:variables
}
