package presentacion;

import presentacion.controles.ControlPantallas;
import dto.EmpleadoDTO;
import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import presentacion.utilerias.GestorSesion;

/**
 *
 * @author saula
 */
public class PanelInformacionEmpleado extends javax.swing.JPanel {
    
    /**
     * Creates new form panelInformacionEmpleadoBien-
     */
    public PanelInformacionEmpleado() {
        initComponents();
        cargarPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnMenuPrincipal = new javax.swing.JButton();
        lblNombreEmpleado = new javax.swing.JLabel();
        lblPuestoEmpleado = new javax.swing.JLabel();
        lblSucursal = new javax.swing.JLabel();
        lblNombreSucursal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 17, 40));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoCine3.png"))); // NOI18N

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenDefault1.png"))); // NOI18N
        lblFoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCerrarSesion.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(148, 163, 184));
        lblCerrarSesion.setText("CERRAR SESIÓN");
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
        });

        lblHora.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblHora.setForeground(new java.awt.Color(241, 245, 249));
        lblHora.setText("00:00");

        lblFecha.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(241, 245, 249));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("05 de septiembre de 2025");

        btnMenuPrincipal.setBackground(new java.awt.Color(37, 99, 235));
        btnMenuPrincipal.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnMenuPrincipal.setText("MENÚ PRINCIPAL");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });

        lblNombreEmpleado.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblNombreEmpleado.setForeground(new java.awt.Color(241, 245, 249));
        lblNombreEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreEmpleado.setText("SAUL APODACA");

        lblPuestoEmpleado.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblPuestoEmpleado.setForeground(new java.awt.Color(241, 245, 249));
        lblPuestoEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuestoEmpleado.setText("GERENTE");

        lblSucursal.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblSucursal.setForeground(new java.awt.Color(241, 245, 249));
        lblSucursal.setText("SUCURSAL:");

        lblNombreSucursal.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblNombreSucursal.setForeground(new java.awt.Color(241, 245, 249));
        lblNombreSucursal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombreSucursal.setText("NAINARI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 161, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lblSucursal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombreSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(lblCerrarSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblHora)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPuestoEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFoto)
                .addGap(34, 34, 34)
                .addComponent(lblNombreEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPuestoEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreSucursal)
                    .addComponent(lblSucursal))
                .addGap(42, 42, 42)
                .addComponent(btnMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFecha)
                .addGap(18, 18, 18)
                .addComponent(lblHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCerrarSesion)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        ControlPantallas.getInstance().abrirMenuPrincipal();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void cargarPanel(){
        cargarInformacionEmpleado();
        mostrarFecha();
        iniciarReloj();
    }
    
    private void mostrarFecha(){
        LocalDate hoy = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd 'de' MMMM 'de' yyyy", new Locale("es", "ES"));
        lblFecha.setText(hoy.format(formato));
    }
    
    private void iniciarReloj(){
         Timer timer = new Timer(1000, e -> {
            LocalTime hora = LocalTime.now();
            DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("HH:mm");
            lblHora.setText(hora.format(formatoHora));
        });
        timer.start();
    }
    
    private void cargarInformacionEmpleado(){
        EmpleadoDTO empleado = GestorSesion.getUsuario();
        configurarImagen(empleado.getUrlFoto());
        configurarInformacion(lblNombreEmpleado, empleado.getNombres()+" "+empleado.getApellidoPaterno());
        configurarInformacion(lblPuestoEmpleado, empleado.getOcupacion());
        configurarInformacion(lblNombreSucursal, empleado.getSucursal());
    }

    private void configurarInformacion(JLabel etiqueta, String texto){
        etiqueta.setText(texto.toUpperCase());
        etiqueta.setForeground(Color.WHITE);
    }
    
    private void configurarImagen(String urlImagen) {
        lblFoto.setText("");
        lblFoto.setHorizontalAlignment(SwingConstants.CENTER);

        URL url = getClass().getResource(urlImagen);
        if (url != null) {
            ImageIcon icon = new ImageIcon(url);
            Image img = icon.getImage().getScaledInstance(165, 229, Image.SCALE_SMOOTH);
            lblFoto.setIcon(new ImageIcon(img));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreEmpleado;
    private javax.swing.JLabel lblNombreSucursal;
    private javax.swing.JLabel lblPuestoEmpleado;
    private javax.swing.JLabel lblSucursal;
    // End of variables declaration//GEN-END:variables
}
