/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import dto.ComboDTO;
import dto.SaborPalomitasDTO;
import dto.TamanoPalomitasDTO;
import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import presentacion.controles.ControlPantallas;
import presentacion.controles.ControlVentaCombo;
import presentacion.utilerias.CardOpcion;

/**
 *
 * @author saula
 */
public class PanelPersonalizacionPalomitas extends javax.swing.JPanel {

    private ComboDTO combo;
    private List<CardOpcion> cardsTam = new ArrayList<>();
    private List<CardOpcion> cardsSab = new ArrayList<>();
    private TamanoPalomitasDTO tamanoSeleccionado;
    private SaborPalomitasDTO saborSeleccionado;
    

    /**
     * Creates new form PanelPersonalizacionPalomitas
     *
     * @param combo
     */
    public PanelPersonalizacionPalomitas(ComboDTO combo) {
        initComponents();
        this.combo = combo;
        lblNombreCombo.setText(combo.getNombre()); // opcional pero recomendado

        cargarTamanios();
        cargarSabores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblNombreCombo = new javax.swing.JLabel();
        lblPersonalizaPalomitas = new javax.swing.JLabel();
        pnlContenedorTamanos = new javax.swing.JPanel();
        lblSeleccionaSabor = new javax.swing.JLabel();
        lblSeleccionaTamano = new javax.swing.JLabel();
        lblSeparador1 = new javax.swing.JLabel();
        lblSeparador2 = new javax.swing.JLabel();
        pnlContenedorSabores = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();

        setBackground(new java.awt.Color(8, 17, 40));

        pnlFondo.setBackground(new java.awt.Color(18, 31, 55));
        pnlFondo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 65, 85), 1, true));

        lblNombreCombo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblNombreCombo.setForeground(new java.awt.Color(148, 163, 184));
        lblNombreCombo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreCombo.setText("Nombre del combo");

        lblPersonalizaPalomitas.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblPersonalizaPalomitas.setForeground(new java.awt.Color(241, 245, 249));
        lblPersonalizaPalomitas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonalizaPalomitas.setText("Personaliza las palomitas");

        pnlContenedorTamanos.setBackground(new java.awt.Color(8, 17, 40));
        pnlContenedorTamanos.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout pnlContenedorTamanosLayout = new javax.swing.GroupLayout(pnlContenedorTamanos);
        pnlContenedorTamanos.setLayout(pnlContenedorTamanosLayout);
        pnlContenedorTamanosLayout.setHorizontalGroup(
            pnlContenedorTamanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlContenedorTamanosLayout.setVerticalGroup(
            pnlContenedorTamanosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        lblSeleccionaSabor.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblSeleccionaSabor.setForeground(new java.awt.Color(241, 245, 249));
        lblSeleccionaSabor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeleccionaSabor.setText("Selecciona el sabor");

        lblSeleccionaTamano.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblSeleccionaTamano.setForeground(new java.awt.Color(241, 245, 249));
        lblSeleccionaTamano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeleccionaTamano.setText("Selecciona el tamaño");

        lblSeparador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeparador1.setText("_______________________________________________________________________________________________________________________________________________________________________________________");

        lblSeparador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeparador2.setText("_______________________________________________________________________________________________________________________________________________________________________________________");

        pnlContenedorSabores.setBackground(new java.awt.Color(8, 17, 40));
        pnlContenedorSabores.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout pnlContenedorSaboresLayout = new javax.swing.GroupLayout(pnlContenedorSabores);
        pnlContenedorSabores.setLayout(pnlContenedorSaboresLayout);
        pnlContenedorSaboresLayout.setHorizontalGroup(
            pnlContenedorSaboresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlContenedorSaboresLayout.setVerticalGroup(
            pnlContenedorSaboresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContenedorTamanos, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                    .addComponent(lblSeparador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPersonalizaPalomitas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSeparador2, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                    .addComponent(lblSeleccionaSabor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContenedorSabores, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlFondoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblSeleccionaTamano, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreCombo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPersonalizaPalomitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeparador1)
                .addGap(41, 41, 41)
                .addComponent(pnlContenedorTamanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeparador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeleccionaSabor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContenedorSabores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlFondoLayout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(lblSeleccionaTamano)
                    .addContainerGap(489, Short.MAX_VALUE)))
        );

        btnVolver.setBackground(new java.awt.Color(37, 99, 235));
        btnVolver.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(26, 51, 83));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(37, 99, 235));
        btnSiguiente.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(26, 51, 83));
        btnSiguiente.setText("SIGUIENTE");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente))
                    .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ControlPantallas.getInstance().abrirPersonalizacionBebidas(combo);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if (tamanoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un tamaño primero.");
            return;
        }

        if (saborSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un sabor primero.");
            return;
        }

        // Guardar en el combo
        combo.setTamanoPalomitasDTO(tamanoSeleccionado);
        combo.setSaborPalomitasDTO(saborSeleccionado);

        // Ir a la siguiente pantalla
        ControlPantallas.getInstance().abrirPersonalizacionBebidas(combo);
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void cargarTamanios() {
        List<TamanoPalomitasDTO> listaTamanos = ControlVentaCombo.getInstance().obtenerTamanosPalomitas();

        pnlContenedorTamanos.setLayout(new FlowLayout(FlowLayout.LEFT, 20, 20));

        for (TamanoPalomitasDTO tam : listaTamanos) {

            CardOpcion card = new CardOpcion(
                    tam.getNombre(),
                    tam.getPrecioExtra(),
                    tam.getRutaImagen()
            );

            card.setOnClick(() -> {
                tamanoSeleccionado = tam;
                cardsTam.forEach(c -> c.deseleccionar());
                card.seleccionar();
            });

            cardsTam.add(card);
            pnlContenedorTamanos.add(card);
        }

        pnlContenedorTamanos.revalidate();
        pnlContenedorTamanos.repaint();
    }

    private void cargarSabores() {
        List<SaborPalomitasDTO> listaSabores = ControlVentaCombo.getInstance().obtenerSaboresPalomitas();
        pnlContenedorSabores.setLayout(new FlowLayout(FlowLayout.LEFT, 20, 20));

        for (SaborPalomitasDTO sab : listaSabores) {

            CardOpcion card = new CardOpcion(
                    sab.getNombre(),
                    sab.getPrecioExtra(),
                    sab.getRutaImagen()
            );

            card.setOnClick(() -> {
                saborSeleccionado = sab;
                cardsSab.forEach(c -> c.deseleccionar());
                card.seleccionar();
            });

            cardsSab.add(card);
            pnlContenedorSabores.add(card);
        }

        pnlContenedorSabores.revalidate();
        pnlContenedorSabores.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblNombreCombo;
    private javax.swing.JLabel lblPersonalizaPalomitas;
    private javax.swing.JLabel lblSeleccionaSabor;
    private javax.swing.JLabel lblSeleccionaTamano;
    private javax.swing.JLabel lblSeparador1;
    private javax.swing.JLabel lblSeparador2;
    private javax.swing.JPanel pnlContenedorSabores;
    private javax.swing.JPanel pnlContenedorTamanos;
    private javax.swing.JPanel pnlFondo;
    // End of variables declaration//GEN-END:variables
}
