/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import dto.ComboDTO;
import dto.DetallePrecioDTO;
import dto.ReciboAlimentoDTO;
import dto.SaborBebidaDTO;
import dto.VentaAlimentoDTO;
import dto.enums.FormaPago;
import itson.negocios_generadorqr.exceptions.QRGeneradorException;
import itson.negocios_vendercombos.exceptions.VentaComboException;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.net.URL;
import java.time.LocalDate;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import presentacion.controles.ControlPantallas;
import presentacion.controles.ControlVentaCombo;
import presentacion.utilerias.GestorSesion;

/**
 *
 * @author saula
 */
public class PanelInformacionPagoCombo extends javax.swing.JPanel {

    private ComboDTO combo;

    /**
     * Creates new form PanelInformacionPagoCombo
     */
    public PanelInformacionPagoCombo(ComboDTO combo) {
        initComponents();
        this.combo = combo;
        pnlDetalles.setLayout(new BoxLayout(pnlDetalles, BoxLayout.Y_AXIS));
        pnlDetalles.setBackground(new Color(8, 17, 40));
        lblNombreCombo.setText(combo.getNombre());

        configurarImagen();
        cargarDetalles();
        configurarPrecios();
        configurarPanelFormaPago();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFormaPago = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pnlImagenCombo = new javax.swing.JPanel();
        lblImagenCombo = new javax.swing.JLabel();
        lblNombreCombo = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        tituloTotal = new javax.swing.JLabel();
        lblSubtotalPrecio = new javax.swing.JLabel();
        tituloSubtotal = new javax.swing.JLabel();
        lblSeparador2 = new javax.swing.JLabel();
        pnlDetalles = new javax.swing.JPanel();
        pnlFormaPago = new javax.swing.JPanel();
        tituloFormaPago = new javax.swing.JLabel();
        rbTarjeta = new javax.swing.JRadioButton();
        rbEfectivo = new javax.swing.JRadioButton();
        imgEfectivo = new javax.swing.JLabel();
        imgTarjeta = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnConfirmarPago = new javax.swing.JButton();

        setBackground(new java.awt.Color(8, 17, 40));

        jPanel1.setBackground(new java.awt.Color(18, 26, 60));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 65, 85), 1, true));

        pnlImagenCombo.setLayout(new java.awt.BorderLayout());

        lblImagenCombo.setText("jLabel1");
        pnlImagenCombo.add(lblImagenCombo, java.awt.BorderLayout.CENTER);

        lblNombreCombo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblNombreCombo.setText("NOMBRE DEL COMBO");

        lblTotal.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal.setText("$00.00");

        tituloTotal.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        tituloTotal.setForeground(new java.awt.Color(255, 255, 255));
        tituloTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tituloTotal.setText("TOTAL:");

        lblSubtotalPrecio.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblSubtotalPrecio.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtotalPrecio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSubtotalPrecio.setText("$00.00");

        tituloSubtotal.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tituloSubtotal.setForeground(new java.awt.Color(255, 255, 255));
        tituloSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tituloSubtotal.setText("SUBTOTAL:");

        lblSeparador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeparador2.setText("_______________________________________________________________________________________________________________________________________________________________________________________");

        pnlDetalles.setBackground(new java.awt.Color(18, 26, 60));

        javax.swing.GroupLayout pnlDetallesLayout = new javax.swing.GroupLayout(pnlDetalles);
        pnlDetalles.setLayout(pnlDetallesLayout);
        pnlDetallesLayout.setHorizontalGroup(
            pnlDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDetallesLayout.setVerticalGroup(
            pnlDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlImagenCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tituloTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSubtotalPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lblSeparador2, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombreCombo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlImagenCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloSubtotal)
                    .addComponent(lblSubtotalPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSeparador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloTotal)
                    .addComponent(lblTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFormaPago.setBackground(new java.awt.Color(18, 26, 60));
        pnlFormaPago.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 65, 85), 1, true));

        tituloFormaPago.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        tituloFormaPago.setForeground(new java.awt.Color(255, 255, 255));
        tituloFormaPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloFormaPago.setText("ESCOGER FORMA DE PAGO");

        rbTarjeta.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        rbTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        rbTarjeta.setText("TARJETA");
        rbTarjeta.setContentAreaFilled(false);
        rbTarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rbTarjeta.setFocusPainted(false);
        rbTarjeta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        rbEfectivo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        rbEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        rbEfectivo.setText("EFECTIVO");
        rbEfectivo.setContentAreaFilled(false);
        rbEfectivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rbEfectivo.setFocusPainted(false);
        rbEfectivo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        imgEfectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/efectivo.png"))); // NOI18N

        imgTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarjeta.png"))); // NOI18N

        javax.swing.GroupLayout pnlFormaPagoLayout = new javax.swing.GroupLayout(pnlFormaPago);
        pnlFormaPago.setLayout(pnlFormaPagoLayout);
        pnlFormaPagoLayout.setHorizontalGroup(
            pnlFormaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormaPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloFormaPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormaPagoLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(pnlFormaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbEfectivo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgEfectivo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFormaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbTarjeta)
                    .addComponent(imgTarjeta))
                .addGap(200, 200, 200))
        );
        pnlFormaPagoLayout.setVerticalGroup(
            pnlFormaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormaPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloFormaPago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormaPagoLayout.createSequentialGroup()
                        .addComponent(imgTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbTarjeta))
                    .addGroup(pnlFormaPagoLayout.createSequentialGroup()
                        .addComponent(imgEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbEfectivo)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnVolver.setBackground(new java.awt.Color(37, 99, 235));
        btnVolver.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(26, 51, 83));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnConfirmarPago.setBackground(new java.awt.Color(37, 99, 235));
        btnConfirmarPago.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnConfirmarPago.setForeground(new java.awt.Color(26, 51, 83));
        btnConfirmarPago.setText("CONFIRMAR PAGO");
        btnConfirmarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmarPago))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFormaPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ControlPantallas.getInstance().abrirPersonalizacionPalomitas(combo);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnConfirmarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPagoActionPerformed
        if (!rbEfectivo.isSelected() && !rbTarjeta.isSelected()) {
            JOptionPane.showMessageDialog(this, "Selecciona una forma de pago.");
            return;
        }

        FormaPago tipoPago = rbEfectivo.isSelected() ? FormaPago.EFECTIVO : FormaPago.TARJETA;

        DetallePrecioDTO detalle = ControlVentaCombo.getInstance().calcularPrecios(combo);
        VentaAlimentoDTO venta = crearVenta(tipoPago, detalle);

        ReciboAlimentoDTO recibo;
        try {
            recibo = procesarVenta(venta);
            if (recibo != null) {
                ControlPantallas.getInstance().abrirInformacionRecibo(recibo);
            }
        } catch (QRGeneradorException | VentaComboException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarPagoActionPerformed

    private void configurarImagen() {
        lblImagenCombo.setText("");
        lblImagenCombo.setHorizontalAlignment(SwingConstants.CENTER);

        URL url = getClass().getResource("/ImagenesCombos/" + this.combo.getRutaImagen());
        if (url != null) {
            ImageIcon icon = new ImageIcon(url);
            Image img = icon.getImage().getScaledInstance(206, 206, Image.SCALE_SMOOTH);
            lblImagenCombo.setIcon(new ImageIcon(img));
        } else {
            lblImagenCombo.setText("🍔");
            lblImagenCombo.setForeground(new Color(205, 205, 205));
        }
    }

    private void cargarDetalles() {
        pnlDetalles.removeAll();

        // Palomitas
        if (combo.getTamanoPalomitasDTO() != null && combo.getSaborPalomitasDTO() != null) {

            String textoPalo = "Palomitas: "
                    + combo.getTamanoPalomitasDTO().getNombre()
                    + ", sabor "
                    + combo.getSaborPalomitasDTO().getNombre();

            pnlDetalles.add(crearLabelDetalle(textoPalo));
        }

        // Bebidas
        if (combo.getBebidas()!= null && !combo.getBebidas().isEmpty()) {

            int index = 1;
            for (SaborBebidaDTO bebida : combo.getBebidas()) {

                String textoBebida = "Bebida " + index + ": " + bebida.getNombre();
                pnlDetalles.add(crearLabelDetalle(textoBebida));
                index++;
            }
        }

        // Dulce
        if (combo.getDulceDTO() != null) {

            String textoDulce = "Dulce: " + combo.getDulceDTO().getNombre();
            pnlDetalles.add(crearLabelDetalle(textoDulce));
        }

        pnlDetalles.revalidate();
        pnlDetalles.repaint();
    }

    private JLabel crearLabelDetalle(String texto) {
        JLabel lbl = new JLabel(texto);
        lbl.setFont(new Font("Comic Sans MS", Font.PLAIN, 20));
        lbl.setForeground(new Color(241, 245, 249));
        lbl.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
        return lbl;
    }

    private void configurarPrecios() {
        DetallePrecioDTO detalle = ControlVentaCombo.getInstance().calcularPrecios(combo);
        lblSubtotalPrecio.setText(String.format("$%.2f", detalle.getSubtotal()));
        lblTotal.setText(String.format("$%.2f", detalle.getTotal()));
    }

    private VentaAlimentoDTO crearVenta(FormaPago tipoPago, DetallePrecioDTO detalle) {
        VentaAlimentoDTO venta = new VentaAlimentoDTO();
        venta.setCombo(combo);
        venta.setEmpleado(GestorSesion.getUsuario());
        venta.setFecha(LocalDate.now());
        venta.setSubtotal(detalle.getSubtotal());
        venta.setTotal(detalle.getTotal());
        venta.setFormaPago(tipoPago);

        return venta;
    }
    
    private ReciboAlimentoDTO procesarVenta(VentaAlimentoDTO venta) throws QRGeneradorException, VentaComboException {
        
        ReciboAlimentoDTO recibo = ControlVentaCombo.getInstance().registrarVenta(venta);

        if (recibo != null) {
            JOptionPane.showMessageDialog(this,
                    "¡Compra realizada con éxito!\nTotal pagado: " + venta.getTotal());
            return recibo;
        } else {
            JOptionPane.showMessageDialog(this,
                    "Error al procesar la venta.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        return null;
    }
    
    private void configurarPanelFormaPago() {
        bgFormaPago.add(rbEfectivo);
        bgFormaPago.add(rbTarjeta);
        rbEfectivo.setSelected(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFormaPago;
    private javax.swing.JButton btnConfirmarPago;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel imgEfectivo;
    private javax.swing.JLabel imgTarjeta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagenCombo;
    private javax.swing.JLabel lblNombreCombo;
    private javax.swing.JLabel lblSeparador2;
    private javax.swing.JLabel lblSubtotalPrecio;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlDetalles;
    private javax.swing.JPanel pnlFormaPago;
    private javax.swing.JPanel pnlImagenCombo;
    private javax.swing.JRadioButton rbEfectivo;
    private javax.swing.JRadioButton rbTarjeta;
    private javax.swing.JLabel tituloFormaPago;
    private javax.swing.JLabel tituloSubtotal;
    private javax.swing.JLabel tituloTotal;
    // End of variables declaration//GEN-END:variables
}
