/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import dto.AsientoDTO;
import dto.FuncionDTO;
import dto.SalaDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JToggleButton;
import presentacion.utilerias.PintorAsientos;

/**
 *
 * @author saula
 */
public class PanelSeleccionAsientos extends javax.swing.JPanel {

    private FuncionDTO funcion;
    private JToggleButton[][] botones;
    
    /**
     * Creates new form PanelSeleccionAsientos
     * @param funcion
     */
    public PanelSeleccionAsientos(FuncionDTO funcion) {
        this.funcion = funcion;
        initComponents();
        SalaDTO sala = funcion.getSala();
        pnlMapaAsientos.setLayout(new GridLayout(sala.getFilas(), sala.getColumnas(), 5, 5 ));
        botones = new JToggleButton[sala.getFilas()][sala.getColumnas()];
        inicializarAsientos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFuncion = new javax.swing.JPanel();
        lblNombreSalaFuncion = new javax.swing.JLabel();
        lblHoraFuncion = new javax.swing.JLabel();
        lblTipoSalaFuncion = new javax.swing.JLabel();
        lblNombrePelicula = new javax.swing.JLabel();
        pnlContenedor = new javax.swing.JPanel();
        pnlPantalla = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlMapaAsientos = new javax.swing.JPanel();

        setBackground(new java.awt.Color(8, 17, 40));

        pnlFuncion.setBackground(new java.awt.Color(18, 31, 55));
        pnlFuncion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 65, 85), 3, true));

        lblNombreSalaFuncion.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblNombreSalaFuncion.setText("SALA 1");

        lblHoraFuncion.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblHoraFuncion.setText("00:00");

        lblTipoSalaFuncion.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblTipoSalaFuncion.setForeground(new java.awt.Color(148, 163, 184));
        lblTipoSalaFuncion.setText("SALA TRADICIONAL");

        lblNombrePelicula.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblNombrePelicula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombrePelicula.setText("NOMBRE DE LA PELÍCULA");

        javax.swing.GroupLayout pnlFuncionLayout = new javax.swing.GroupLayout(pnlFuncion);
        pnlFuncion.setLayout(pnlFuncionLayout);
        pnlFuncionLayout.setHorizontalGroup(
            pnlFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFuncionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFuncionLayout.createSequentialGroup()
                        .addComponent(lblHoraFuncion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlFuncionLayout.createSequentialGroup()
                        .addComponent(lblNombreSalaFuncion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(lblNombrePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(lblTipoSalaFuncion)))
                .addContainerGap())
        );
        pnlFuncionLayout.setVerticalGroup(
            pnlFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFuncionLayout.createSequentialGroup()
                .addGroup(pnlFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreSalaFuncion)
                    .addGroup(pnlFuncionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoSalaFuncion)
                            .addComponent(lblNombrePelicula))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHoraFuncion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlContenedor.setBackground(new java.awt.Color(18, 26, 60));

        pnlPantalla.setBackground(new java.awt.Color(22, 25, 26));
        pnlPantalla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(32, 40, 76), 1, true));
        pnlPantalla.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(99, 106, 141));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PANTALLA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlPantalla.add(jLabel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlMapaAsientosLayout = new javax.swing.GroupLayout(pnlMapaAsientos);
        pnlMapaAsientos.setLayout(pnlMapaAsientosLayout);
        pnlMapaAsientosLayout.setHorizontalGroup(
            pnlMapaAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );
        pnlMapaAsientosLayout.setVerticalGroup(
            pnlMapaAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenedorLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlMapaAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(102, 102, 102))
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlMapaAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(pnlFuncion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarAsientos(){
        for (AsientoDTO asiento : funcion.getAsientos()){
            int fila = asiento.getFila();
            int columna = asiento.getColumna();
            
            JToggleButton btn = crearBotonAsiento(asiento);
            botones[fila][columna] = btn;
            pnlMapaAsientos.add(btn);
        }
    }

    private JToggleButton crearBotonAsiento(AsientoDTO asiento) {
        JToggleButton btn = new JToggleButton((asiento.getFila() + 1) + "-" + (asiento.getColumna() + 1));
        btn.setPreferredSize(new Dimension(40, 40));

        PintorAsientos.aplicarEstilo(btn, asiento.getEstado());

        configurarEventoSeleccion(btn, asiento);
        return btn;
    }

    private void configurarEventoSeleccion(JToggleButton btn, AsientoDTO asiento) {
        btn.addActionListener(e -> {
            if (btn.isSelected()) {
                btn.setBackground(new Color(14, 93, 70));
            } else {
                PintorAsientos.aplicarEstilo(btn, asiento.getEstado());
            }
        });
    }

    private List<AsientoDTO> obtenerAsientosSeleccionados(){
        return funcion.getAsientos().stream()
                .filter(a ->{
                    JToggleButton b = botones[a.getFila()][a.getColumna()];
                    return b.isSelected();
                }).toList();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHoraFuncion;
    private javax.swing.JLabel lblNombrePelicula;
    private javax.swing.JLabel lblNombreSalaFuncion;
    private javax.swing.JLabel lblTipoSalaFuncion;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlFuncion;
    private javax.swing.JPanel pnlMapaAsientos;
    private javax.swing.JPanel pnlPantalla;
    // End of variables declaration//GEN-END:variables
}
