package presentacion;

import dto.BoletoDTO;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.time.format.DateTimeFormatter;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;
import presentacion.controles.ControlVentaBoleto;

/**
 *
 * @author Saul Isaac Apodaca Baldenegro - 00000252020
 * @author Alejandro Rodríguez Lugo - 00000251622
 */
public class PanelInformacionBoleto extends javax.swing.JPanel {

    private BoletoDTO boleto;

    /**
     * Creates new form PanelInformacionBoleto
     *
     * @param boleto
     */
    public PanelInformacionBoleto(BoletoDTO boleto) {
        this.boleto = boleto;
        initComponents();
        cargarBoleto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCorreo = new javax.swing.JTextField();
        btnEnviarBoleto = new javax.swing.JButton();
        pnlVisorPDF = new javax.swing.JScrollPane();
        lblPdf = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 17, 40));

        txtCorreo.setBackground(new java.awt.Color(31, 41, 55));
        txtCorreo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnEnviarBoleto.setBackground(new java.awt.Color(37, 99, 235));
        btnEnviarBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnEnviarBoleto.setForeground(new java.awt.Color(26, 51, 83));
        btnEnviarBoleto.setText("ENVIAR BOLETO");
        btnEnviarBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarBoletoActionPerformed(evt);
            }
        });

        lblPdf.setText("jLabel1");
        pnlVisorPDF.setViewportView(lblPdf);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnEnviarBoleto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(pnlVisorPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(pnlVisorPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCorreo)
                    .addComponent(btnEnviarBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarBoletoActionPerformed
        try {
            if (txtCorreo.getText().isEmpty() || txtCorreo.getText().equals("") || txtCorreo.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Ingresa un correo.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
            String correo = txtCorreo.getText().trim();
            String regex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
            if (!correo.matches(regex)) {
                JOptionPane.showMessageDialog(this, "El correo no tiene un formato válido.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
            byte[] pdfBytes = ControlVentaBoleto.getInstance().generarPDFBoleto(boleto);
            if (pdfBytes == null) {
                JOptionPane.showMessageDialog(this, "No se pudo generar el boleto.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            ControlVentaBoleto.getInstance().mandarCorreo(txtCorreo.getText().strip(), "Confirmación de boleto - " + boleto.getVenta().getFuncion().getPelicula().getTitulo(), estructuraMensaje(), pdfBytes);
            JOptionPane.showMessageDialog(this, "El correo ha sido enviado.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            return;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al enviar el boleto.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnEnviarBoletoActionPerformed

    private void cargarBoleto() {
        try {
            byte[] pdfBytes = ControlVentaBoleto.getInstance().generarPDFBoleto(boleto);
            if (pdfBytes == null) {
                return;
            }
            PDDocument doc = PDDocument.load(pdfBytes);
            PDFRenderer renderer = new PDFRenderer(doc);
            BufferedImage image = renderer.renderImageWithDPI(0, 150);
            doc.close();
            lblPdf.setIcon(new ImageIcon(image));
            pnlVisorPDF.setViewportView(lblPdf);
            pnlVisorPDF.revalidate();
            pnlVisorPDF.repaint();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se pudo mostrar el PDF: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Método que da estructura al cuerpo del correo.
     *
     * @return Estructura del cuerpo que será enviado.
     */
    private String estructuraMensaje() {
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        String fecha = boleto.getVenta().getFuncion().getFechaHora().format(fmt);
        String asientos = String.join(", ", boleto.getVenta().getAsientos().stream().map(Object::toString).toList()
        );
        return """
        <h2>Confirmación de compra</h2>
        <p>Estos son los detalles de tu compra. ¡Disfruta tu experiencia!</p>
        <p><b>Película:</b> %s</p>
        <p><b>Fecha y horario:</b> %s</p>
        <p><b>Sala:</b> %s</p>
        <p><b>Asientos:</b> %s</p>
        <p><b>Total:</b> $%.2f</p>""".formatted(boleto.getVenta().getFuncion().getPelicula().getTitulo(), fecha,
                boleto.getVenta().getFuncion().getSala().getNombre(), asientos, boleto.getVenta().getTotal()
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarBoleto;
    private javax.swing.JLabel lblPdf;
    private javax.swing.JScrollPane pnlVisorPDF;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
