package presentacion;

import dto.ComboDTO;
import dto.FiltroDTO;
import exceptions.ComboException;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.net.URL;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import presentacion.controles.ControlPantallas;
import presentacion.controles.ControlVentaCombo;

/**
 *
 * @author saula
 */
public class PanelSeleccionCombos extends javax.swing.JPanel {

    private List<JLabel> etiquetasImagenes;
    private List<JLabel> etiquetasNombres;
    
    /**
     * Creates new form PanelSeleccionCombos
     */
    public PanelSeleccionCombos() {
        initComponents();
        inicializarReferencias();
        panelDeBuscador1.setOnBusquedaChange((texto) -> {
            actualizarCombos();
        });
        panelPaginacion1.setOnPaginaChange(() -> {
            actualizarCombos();
        });
        actualizarCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCombos = new javax.swing.JPanel();
        pnlCombo1 = new javax.swing.JPanel();
        pnlInfoCombo1 = new javax.swing.JPanel();
        lblNombreCombo1 = new javax.swing.JLabel();
        lblImagenCombo1 = new javax.swing.JLabel();
        pnlCombo2 = new javax.swing.JPanel();
        pnlInfoCombo2 = new javax.swing.JPanel();
        lblNombreCombo2 = new javax.swing.JLabel();
        lblImagenCombo2 = new javax.swing.JLabel();
        pnlCombo3 = new javax.swing.JPanel();
        pnlInfoCombo3 = new javax.swing.JPanel();
        lblNombreCombo3 = new javax.swing.JLabel();
        lblImagenCombo3 = new javax.swing.JLabel();
        pnlCombo4 = new javax.swing.JPanel();
        pnlInfoCombo4 = new javax.swing.JPanel();
        lblNombreCombo4 = new javax.swing.JLabel();
        lblImagenCombo4 = new javax.swing.JLabel();
        pnlCombo5 = new javax.swing.JPanel();
        pnlInfoCombo5 = new javax.swing.JPanel();
        lblNombreCombo5 = new javax.swing.JLabel();
        lblImagenCombo5 = new javax.swing.JLabel();
        pnlCombo6 = new javax.swing.JPanel();
        pnlInfoCombo6 = new javax.swing.JPanel();
        lblNombreCombo6 = new javax.swing.JLabel();
        lblImagenCombo6 = new javax.swing.JLabel();
        panelPaginacion1 = new presentacion.utilerias.PanelPaginacion();
        panelDeBuscador1 = new presentacion.utilerias.PanelDeBuscador();

        setBackground(new java.awt.Color(8, 17, 40));

        panelCombos.setBackground(new java.awt.Color(8, 17, 40));
        panelCombos.setLayout(new java.awt.GridLayout(0, 3, 10, 10));

        pnlCombo1.setBackground(new java.awt.Color(8, 17, 40));
        pnlCombo1.setLayout(new java.awt.GridBagLayout());

        pnlInfoCombo1.setBackground(new java.awt.Color(8, 17, 40));
        pnlInfoCombo1.setPreferredSize(new java.awt.Dimension(165, 250));
        pnlInfoCombo1.setLayout(new java.awt.BorderLayout());

        lblNombreCombo1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        pnlInfoCombo1.add(lblNombreCombo1, java.awt.BorderLayout.PAGE_END);

        lblImagenCombo1.setText("jLabel1");
        pnlInfoCombo1.add(lblImagenCombo1, java.awt.BorderLayout.CENTER);

        pnlCombo1.add(pnlInfoCombo1, new java.awt.GridBagConstraints());

        panelCombos.add(pnlCombo1);

        pnlCombo2.setBackground(new java.awt.Color(8, 17, 40));

        pnlInfoCombo2.setBackground(new java.awt.Color(8, 17, 40));
        pnlInfoCombo2.setPreferredSize(new java.awt.Dimension(165, 250));
        pnlInfoCombo2.setLayout(new java.awt.BorderLayout());

        lblNombreCombo2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblNombreCombo2.setText("g");
        pnlInfoCombo2.add(lblNombreCombo2, java.awt.BorderLayout.PAGE_END);

        lblImagenCombo2.setText("jLabel1");
        pnlInfoCombo2.add(lblImagenCombo2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlCombo2Layout = new javax.swing.GroupLayout(pnlCombo2);
        pnlCombo2.setLayout(pnlCombo2Layout);
        pnlCombo2Layout.setHorizontalGroup(
            pnlCombo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
            .addGroup(pnlCombo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCombo2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlInfoCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlCombo2Layout.setVerticalGroup(
            pnlCombo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
            .addGroup(pnlCombo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCombo2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlInfoCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelCombos.add(pnlCombo2);

        pnlCombo3.setBackground(new java.awt.Color(8, 17, 40));

        pnlInfoCombo3.setBackground(new java.awt.Color(8, 17, 40));
        pnlInfoCombo3.setPreferredSize(new java.awt.Dimension(165, 250));
        pnlInfoCombo3.setLayout(new java.awt.BorderLayout());

        lblNombreCombo3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        pnlInfoCombo3.add(lblNombreCombo3, java.awt.BorderLayout.PAGE_END);

        lblImagenCombo3.setText("jLabel1");
        pnlInfoCombo3.add(lblImagenCombo3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlCombo3Layout = new javax.swing.GroupLayout(pnlCombo3);
        pnlCombo3.setLayout(pnlCombo3Layout);
        pnlCombo3Layout.setHorizontalGroup(
            pnlCombo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
            .addGroup(pnlCombo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCombo3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlInfoCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlCombo3Layout.setVerticalGroup(
            pnlCombo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
            .addGroup(pnlCombo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCombo3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlInfoCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelCombos.add(pnlCombo3);

        pnlCombo4.setBackground(new java.awt.Color(8, 17, 40));

        pnlInfoCombo4.setBackground(new java.awt.Color(8, 17, 40));
        pnlInfoCombo4.setPreferredSize(new java.awt.Dimension(165, 250));
        pnlInfoCombo4.setLayout(new java.awt.BorderLayout());

        lblNombreCombo4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        pnlInfoCombo4.add(lblNombreCombo4, java.awt.BorderLayout.PAGE_END);

        lblImagenCombo4.setText("jLabel1");
        pnlInfoCombo4.add(lblImagenCombo4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlCombo4Layout = new javax.swing.GroupLayout(pnlCombo4);
        pnlCombo4.setLayout(pnlCombo4Layout);
        pnlCombo4Layout.setHorizontalGroup(
            pnlCombo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
            .addGroup(pnlCombo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCombo4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlInfoCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlCombo4Layout.setVerticalGroup(
            pnlCombo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
            .addGroup(pnlCombo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCombo4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlInfoCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelCombos.add(pnlCombo4);

        pnlCombo5.setBackground(new java.awt.Color(8, 17, 40));

        pnlInfoCombo5.setBackground(new java.awt.Color(8, 17, 40));
        pnlInfoCombo5.setPreferredSize(new java.awt.Dimension(165, 250));
        pnlInfoCombo5.setLayout(new java.awt.BorderLayout());

        lblNombreCombo5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        pnlInfoCombo5.add(lblNombreCombo5, java.awt.BorderLayout.PAGE_END);

        lblImagenCombo5.setText("jLabel1");
        pnlInfoCombo5.add(lblImagenCombo5, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlCombo5Layout = new javax.swing.GroupLayout(pnlCombo5);
        pnlCombo5.setLayout(pnlCombo5Layout);
        pnlCombo5Layout.setHorizontalGroup(
            pnlCombo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
            .addGroup(pnlCombo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCombo5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlInfoCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlCombo5Layout.setVerticalGroup(
            pnlCombo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
            .addGroup(pnlCombo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCombo5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlInfoCombo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelCombos.add(pnlCombo5);

        pnlCombo6.setBackground(new java.awt.Color(8, 17, 40));

        pnlInfoCombo6.setBackground(new java.awt.Color(8, 17, 40));
        pnlInfoCombo6.setPreferredSize(new java.awt.Dimension(165, 250));
        pnlInfoCombo6.setLayout(new java.awt.BorderLayout());

        lblNombreCombo6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        pnlInfoCombo6.add(lblNombreCombo6, java.awt.BorderLayout.PAGE_END);

        lblImagenCombo6.setText("jLabel1");
        pnlInfoCombo6.add(lblImagenCombo6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlCombo6Layout = new javax.swing.GroupLayout(pnlCombo6);
        pnlCombo6.setLayout(pnlCombo6Layout);
        pnlCombo6Layout.setHorizontalGroup(
            pnlCombo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
            .addGroup(pnlCombo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCombo6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlInfoCombo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlCombo6Layout.setVerticalGroup(
            pnlCombo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
            .addGroup(pnlCombo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCombo6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlInfoCombo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelCombos.add(pnlCombo6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(panelPaginacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDeBuscador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(panelCombos, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(70, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelDeBuscador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 637, Short.MAX_VALUE)
                .addComponent(panelPaginacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(89, 89, 89)
                    .addComponent(panelCombos, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(89, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que se encarga de cargar la pantalla con los combos
     */
    private void cargarCombos(List<ComboDTO> combos) {
        for (int i = 0; i < etiquetasImagenes.size(); i++) {
            JLabel lblImagen = etiquetasImagenes.get(i);
            JLabel lblNombre = etiquetasNombres.get(i);

            limpiarEtiquetas(lblImagen, lblNombre);

            if (i < combos.size()) {
                ComboDTO combo = combos.get(i);
                mostrarComboEnEtiqueta(combo, lblImagen, lblNombre);
            }
        }
    }
    
    /**
     * Configura el nombre, imagen y eventos del click sobre un combo
     *
     * @param combo la dto del combo a configurar
     * @param lblImagen etiqueta en dónde se configurará la imagen
     * @param lblNombre etiqueta en dónde se configurará el nombre
     */
    private void mostrarComboEnEtiqueta(ComboDTO combo, JLabel lblImagen, JLabel lblNombre) {
        configurarTitulo(lblNombre, combo.getNombre());
        configurarImagen(lblImagen, combo.getRutaImagen());
        configurarEventoClick(lblImagen, combo);
    }
    
    /**
     * Método para limpiar las etiquetas dónde irá la información de los
     * combos
     *
     * @param lblImagen etiqueta dónde va la imagen del combo
     * @param lblNombre etiqueta donde va el nombre del combo
     */
    private void limpiarEtiquetas(JLabel lblImagen, JLabel lblNombre) {
        lblImagen.setIcon(null);
        lblImagen.setText("");
        lblNombre.setText("");
    }
    
    /**
     * Método que inicializa las referencias de dónde se mostrar la información
     * del combo
     */
    private void inicializarReferencias() {
        etiquetasImagenes = List.of(
                lblImagenCombo1, lblImagenCombo2, lblImagenCombo3,
                lblImagenCombo4, lblImagenCombo5, lblImagenCombo6
        );

        etiquetasNombres = List.of(
                lblNombreCombo1, lblNombreCombo2, lblNombreCombo3,
                lblNombreCombo4, lblNombreCombo5, lblNombreCombo6
        );
    }

    /**
     * Asocia evento de los clicks sobre la imagen del combo
     *
     * @param lblImagen etiqueta de la imagen del combo que es de donde
     * escuchará el click
     * @param combo se envía el dto para posteriores configuraciones
     */
    private void configurarEventoClick(JLabel lblImagen, ComboDTO combo) {
        lblImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                ControlPantallas.getInstance().abrirDetalleCombo(combo);
            }
        });
    }
    
    /**
     * Carga y escala la imagen de las guardadas en recursos
     *
     * @param lblImagen etiqueta dónde va la imagen del combo
     * @param rutaImagen path del nombre del archivo de la imagen
     */
    private void configurarImagen(JLabel lblImagen, String rutaImagen) {
        lblImagen.setHorizontalAlignment(SwingConstants.CENTER);
        lblImagen.setCursor(new Cursor(Cursor.HAND_CURSOR));

        URL url = getClass().getResource("/ImagenesCombos/" + rutaImagen);
        if (url != null) {
            ImageIcon icon = new ImageIcon(url);
            Image img = icon.getImage().getScaledInstance(229, 229, Image.SCALE_SMOOTH);
            lblImagen.setIcon(new ImageIcon(img));
        } else {
            lblImagen.setText("🍬");
            lblImagen.setForeground(new Color(205, 205, 205));
        }
    }
    
    /**
     * Formatea el nombre de los combos
     *
     * @param lblNombre etiqueta dónde va el nombre del combo
     * @param nombre el nombre que se pondrá en la etiqueta
     */
    private void configurarTitulo(JLabel lblNombre, String nombre) {
        lblNombre.setHorizontalAlignment(SwingConstants.CENTER);
        lblNombre.setText(nombre.toUpperCase());
        lblNombre.setForeground(new Color(205, 205, 205));
    }
    
    private void actualizarCombos() {
        String busqueda = panelDeBuscador1.getTextoBusqueda();
        int pagina = panelPaginacion1.getPaginaActual();  
        int tamano = panelPaginacion1.getTamanoPagina();     

        FiltroDTO filtro = new FiltroDTO(pagina, tamano, busqueda);
        try{
            List<ComboDTO> combos = ControlVentaCombo.getInstance().obtenerCombos(filtro);
            cargarCombos(combos);    
        } catch (ComboException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error",  JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImagenCombo1;
    private javax.swing.JLabel lblImagenCombo2;
    private javax.swing.JLabel lblImagenCombo3;
    private javax.swing.JLabel lblImagenCombo4;
    private javax.swing.JLabel lblImagenCombo5;
    private javax.swing.JLabel lblImagenCombo6;
    private javax.swing.JLabel lblNombreCombo1;
    private javax.swing.JLabel lblNombreCombo2;
    private javax.swing.JLabel lblNombreCombo3;
    private javax.swing.JLabel lblNombreCombo4;
    private javax.swing.JLabel lblNombreCombo5;
    private javax.swing.JLabel lblNombreCombo6;
    private javax.swing.JPanel panelCombos;
    private presentacion.utilerias.PanelDeBuscador panelDeBuscador1;
    private presentacion.utilerias.PanelPaginacion panelPaginacion1;
    private javax.swing.JPanel pnlCombo1;
    private javax.swing.JPanel pnlCombo2;
    private javax.swing.JPanel pnlCombo3;
    private javax.swing.JPanel pnlCombo4;
    private javax.swing.JPanel pnlCombo5;
    private javax.swing.JPanel pnlCombo6;
    private javax.swing.JPanel pnlInfoCombo1;
    private javax.swing.JPanel pnlInfoCombo2;
    private javax.swing.JPanel pnlInfoCombo3;
    private javax.swing.JPanel pnlInfoCombo4;
    private javax.swing.JPanel pnlInfoCombo5;
    private javax.swing.JPanel pnlInfoCombo6;
    // End of variables declaration//GEN-END:variables
}
