package presentacion;

import dto.FuncionDTO;
import dto.PeliculaDTO;
import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import java.util.Arrays;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author saula
 */
public class PanelSeleccionFuncion extends javax.swing.JPanel {
    
    private List<JLabel> etiquetasNombreSala;
    private List<JLabel> etiquetasHoraFuncion;
    private List<JLabel> etiquetasTipoSala;
    private List<JPanel> panelesFunciones;
    
    /**
     * Creates new form PanelSeleccionFuncion
     * @param pelicula
     */
    public PanelSeleccionFuncion(PeliculaDTO pelicula) {
        initComponents();
        inicializarReferencias();
        cargarInformacionPelicula(pelicula);
        cargarFunciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlImagenPelicula = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        panelPaginacion1 = new presentacion.utilerias.PanelPaginacion();
        pnlFuncion1 = new javax.swing.JPanel();
        lblNombreSalaFuncion1 = new javax.swing.JLabel();
        lblHoraFuncion1 = new javax.swing.JLabel();
        lblTipoSalaFuncion1 = new javax.swing.JLabel();
        lblTituloPelicula = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblIdioma = new javax.swing.JLabel();
        datePicker = new datechooser.beans.DateChooserCombo();
        btnVolver = new javax.swing.JButton();
        pnlFuncion2 = new javax.swing.JPanel();
        lblNombreSalaFuncion2 = new javax.swing.JLabel();
        lblHoraFuncion2 = new javax.swing.JLabel();
        lblTipoSalaFuncion2 = new javax.swing.JLabel();
        pnlFuncion3 = new javax.swing.JPanel();
        lblNombreSalaFuncion3 = new javax.swing.JLabel();
        lblHoraFuncion3 = new javax.swing.JLabel();
        lblTipoSalaFuncion3 = new javax.swing.JLabel();
        pnlFuncion4 = new javax.swing.JPanel();
        lblNombreSalaFuncion4 = new javax.swing.JLabel();
        lblHoraFuncion4 = new javax.swing.JLabel();
        lblTipoSalaFuncion4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 17, 40));

        pnlImagenPelicula.setLayout(new java.awt.BorderLayout());

        lblImagen.setText("jLabel4");
        pnlImagenPelicula.add(lblImagen, java.awt.BorderLayout.CENTER);

        pnlFuncion1.setBackground(new java.awt.Color(18, 31, 55));
        pnlFuncion1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 65, 85), 3, true));

        lblNombreSalaFuncion1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblNombreSalaFuncion1.setText("SALA 1");

        lblHoraFuncion1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblHoraFuncion1.setText("00:00");

        lblTipoSalaFuncion1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblTipoSalaFuncion1.setForeground(new java.awt.Color(148, 163, 184));
        lblTipoSalaFuncion1.setText("SALA TRADICIONAL");

        javax.swing.GroupLayout pnlFuncion1Layout = new javax.swing.GroupLayout(pnlFuncion1);
        pnlFuncion1.setLayout(pnlFuncion1Layout);
        pnlFuncion1Layout.setHorizontalGroup(
            pnlFuncion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFuncion1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblNombreSalaFuncion1)
                .addGap(272, 272, 272)
                .addComponent(lblHoraFuncion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(lblTipoSalaFuncion1)
                .addGap(18, 18, 18))
        );
        pnlFuncion1Layout.setVerticalGroup(
            pnlFuncion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFuncion1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(pnlFuncion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreSalaFuncion1)
                    .addComponent(lblHoraFuncion1))
                .addContainerGap())
            .addGroup(pnlFuncion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTipoSalaFuncion1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTituloPelicula.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTituloPelicula.setText("TITULO DE LA PELÍCULA");

        lblDuracion.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblDuracion.setForeground(new java.awt.Color(148, 163, 184));
        lblDuracion.setText("DURACIÓN");

        lblIdioma.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblIdioma.setForeground(new java.awt.Color(148, 163, 184));
        lblIdioma.setText("IDIOMA");

        datePicker.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(204, 204, 204),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(204, 204, 204),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(204, 204, 204),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(204, 204, 204),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    datePicker.setFieldFont(new java.awt.Font("Comic Sans MS", java.awt.Font.BOLD, 12));

    btnVolver.setBackground(new java.awt.Color(37, 99, 235));
    btnVolver.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
    btnVolver.setForeground(new java.awt.Color(26, 51, 83));
    btnVolver.setText("VOLVER");
    btnVolver.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnVolverActionPerformed(evt);
        }
    });

    pnlFuncion2.setBackground(new java.awt.Color(18, 31, 55));
    pnlFuncion2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 65, 85), 3, true));

    lblNombreSalaFuncion2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
    lblNombreSalaFuncion2.setText("SALA 1");

    lblHoraFuncion2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
    lblHoraFuncion2.setText("00:00");

    lblTipoSalaFuncion2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
    lblTipoSalaFuncion2.setForeground(new java.awt.Color(148, 163, 184));
    lblTipoSalaFuncion2.setText("SALA TRADICIONAL");

    javax.swing.GroupLayout pnlFuncion2Layout = new javax.swing.GroupLayout(pnlFuncion2);
    pnlFuncion2.setLayout(pnlFuncion2Layout);
    pnlFuncion2Layout.setHorizontalGroup(
        pnlFuncion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlFuncion2Layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(lblNombreSalaFuncion2)
            .addGap(272, 272, 272)
            .addComponent(lblHoraFuncion2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTipoSalaFuncion2)
            .addGap(18, 18, 18))
    );
    pnlFuncion2Layout.setVerticalGroup(
        pnlFuncion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFuncion2Layout.createSequentialGroup()
            .addContainerGap(23, Short.MAX_VALUE)
            .addGroup(pnlFuncion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblNombreSalaFuncion2)
                .addComponent(lblHoraFuncion2))
            .addContainerGap())
        .addGroup(pnlFuncion2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblTipoSalaFuncion2)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pnlFuncion3.setBackground(new java.awt.Color(18, 31, 55));
    pnlFuncion3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 65, 85), 3, true));

    lblNombreSalaFuncion3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
    lblNombreSalaFuncion3.setText("SALA 1");

    lblHoraFuncion3.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
    lblHoraFuncion3.setText("00:00");

    lblTipoSalaFuncion3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
    lblTipoSalaFuncion3.setForeground(new java.awt.Color(148, 163, 184));
    lblTipoSalaFuncion3.setText("SALA TRADICIONAL");

    javax.swing.GroupLayout pnlFuncion3Layout = new javax.swing.GroupLayout(pnlFuncion3);
    pnlFuncion3.setLayout(pnlFuncion3Layout);
    pnlFuncion3Layout.setHorizontalGroup(
        pnlFuncion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlFuncion3Layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(lblNombreSalaFuncion3)
            .addGap(272, 272, 272)
            .addComponent(lblHoraFuncion3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTipoSalaFuncion3)
            .addGap(18, 18, 18))
    );
    pnlFuncion3Layout.setVerticalGroup(
        pnlFuncion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFuncion3Layout.createSequentialGroup()
            .addContainerGap(23, Short.MAX_VALUE)
            .addGroup(pnlFuncion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblNombreSalaFuncion3)
                .addComponent(lblHoraFuncion3))
            .addContainerGap())
        .addGroup(pnlFuncion3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblTipoSalaFuncion3)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pnlFuncion4.setBackground(new java.awt.Color(18, 31, 55));
    pnlFuncion4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 65, 85), 3, true));

    lblNombreSalaFuncion4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
    lblNombreSalaFuncion4.setText("SALA 1");

    lblHoraFuncion4.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
    lblHoraFuncion4.setText("00:00");

    lblTipoSalaFuncion4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
    lblTipoSalaFuncion4.setForeground(new java.awt.Color(148, 163, 184));
    lblTipoSalaFuncion4.setText("SALA TRADICIONAL");

    javax.swing.GroupLayout pnlFuncion4Layout = new javax.swing.GroupLayout(pnlFuncion4);
    pnlFuncion4.setLayout(pnlFuncion4Layout);
    pnlFuncion4Layout.setHorizontalGroup(
        pnlFuncion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnlFuncion4Layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(lblNombreSalaFuncion4)
            .addGap(272, 272, 272)
            .addComponent(lblHoraFuncion4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTipoSalaFuncion4)
            .addGap(18, 18, 18))
    );
    pnlFuncion4Layout.setVerticalGroup(
        pnlFuncion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFuncion4Layout.createSequentialGroup()
            .addContainerGap(23, Short.MAX_VALUE)
            .addGroup(pnlFuncion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblNombreSalaFuncion4)
                .addComponent(lblHoraFuncion4))
            .addContainerGap())
        .addGroup(pnlFuncion4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblTipoSalaFuncion4)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(50, 50, 50)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnlImagenPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblIdioma)
                                .addComponent(lblDuracion)
                                .addComponent(lblTituloPelicula)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPaginacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(pnlFuncion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFuncion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFuncion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFuncion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(56, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(lblTituloPelicula)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblDuracion)
                    .addGap(4, 4, 4)
                    .addComponent(lblIdioma))
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlImagenPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(18, 18, 18)
            .addComponent(pnlFuncion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(pnlFuncion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(pnlFuncion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(pnlFuncion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(15, 15, 15))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panelPaginacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    }// </editor-fold>//GEN-END:initComponents
    /**
     *Al picarle al botón volver mandará a la pantalla anterior
     * @param evt el evento que hará
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ControlPantallas.getInstance().abrirSeleccionPeliculas(this);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * Método que se encargará de cargar la información de la película
     * 
     * @param pelicula película a mostrar
     */
    private void cargarInformacionPelicula(PeliculaDTO pelicula) {
        configurarImagen(pelicula.getRutaImagen());
        configurarTitulo(pelicula.getTitulo());
        configurarInformacionPelicula(pelicula.getDuracion(), pelicula.getIdioma());
    }

    /**
     * Carga y escala la imagen de las guardadas en recursos
     *
     * @param lblImagen etiqueta dónde va la imagen de la película
     * @param rutaImagen path del nombre del archivo de la imagen
     */
    private void configurarImagen(String rutaImagen) {
        lblImagen.setText("");
        lblImagen.setHorizontalAlignment(SwingConstants.CENTER);

        URL url = getClass().getResource(rutaImagen);
        if (url != null) {
            ImageIcon icon = new ImageIcon(url);
            Image img = icon.getImage().getScaledInstance(165, 229, Image.SCALE_SMOOTH);
            lblImagen.setIcon(new ImageIcon(img));
        } else {
            lblImagen.setText("🎬");
            lblImagen.setForeground(new Color(204, 204, 204));
        }
    }
    
    /**
     * Formatea el título de la película en la etiqueta
     * 
     * @param titulo el título que se pondrá en la etiqueta
     */
    private void configurarTitulo(String titulo){
        lblTituloPelicula.setText(titulo.toUpperCase());
        lblTituloPelicula.setForeground(new Color(204, 204, 204));
    }

    /**
     * Formatea la información de la película que se mostrará
     *
     * @param duracion la duración que tiene la película en minutos
     * @param idioma el idioma en el que estará la película
     */
    private void configurarInformacionPelicula(String duracion, String idioma) {
        lblDuracion.setText(duracion);
        lblDuracion.setForeground(new Color(148, 163, 184));
        lblIdioma.setText(idioma);
        lblIdioma.setForeground(new Color(148, 163, 184));
    }

    /**
     * Método que se encarga de cargar la pantalla con las funciones
     */
    private void cargarFunciones() {
        List<FuncionDTO> funciones = obtenerListaFunciones();

        for (int i = 0; i < etiquetasNombreSala.size(); i++) {
            JLabel lblNombreSala = etiquetasNombreSala.get(i);
            JLabel lblHoraFuncion = etiquetasHoraFuncion.get(i);
            JLabel lblTipoSala = etiquetasTipoSala.get(i);
            JPanel pnlFuncion = panelesFunciones.get(i);

            limpiarEtiquetas(lblNombreSala, lblHoraFuncion, lblTipoSala);

            if (i < funciones.size()) {
                FuncionDTO funcion = funciones.get(i);
                mostrarFuncionEtiqueta(funcion, lblNombreSala, lblHoraFuncion, lblTipoSala, pnlFuncion);

            }

        }
    }

    /**
     * Configura el nombre de la sala, horario de la funcion, el tipo de sala y
     * eventos del click sobre una función
     *
     * @param funcion DTO de la función de la película a configurar
     * @param lblNombreSala etiqueta en dónde se configurará el nombre de la
     * sala
     * @param lblHoraFuncion etiqueta en dónde se configurará el horario de la
     * función
     * @param lblTipoSala etiqueta en dónde se configurará el nombre del tipo de
     * sala
     * @param panelFuncion panel en dónde se configurará el evento del click
     * para la elección de función
     */
    private void mostrarFuncionEtiqueta(FuncionDTO funcion, JLabel lblNombreSala, JLabel lblHoraFuncion, JLabel lblTipoSala, JPanel panelFuncion) {
        configurarNombreSala(lblNombreSala, funcion.getNombreSala());
        configurarHoraFuncion(lblHoraFuncion, funcion.getHoraFuncion());
        configurarTipoSala(lblTipoSala, funcion.getTipoSala());
        configurarEventoClick(panelFuncion, funcion);
    }

    /**
     * Formatea el nombre de la sala en las etiquetas
     *
     * @param lblNombreSala etiqueta dónde va el nombre de la sala
     * @param nombreSala nombre de la sala que se pondrá en la etiqueta
     */
    private void configurarNombreSala(JLabel lblNombreSala, String nombreSala) {
        lblNombreSala.setText(nombreSala);
        lblNombreSala.setForeground(new Color(204, 204, 204));
    }

    /**
     * Formatea la hora de la función en las etiquetas
     *
     * @param lblHoraFuncion etiqueta dónde va la hora de la función
     * @param horaFuncion la hora en la que la función iniciará
     */
    private void configurarHoraFuncion(JLabel lblHoraFuncion, String horaFuncion) {
        lblHoraFuncion.setText(horaFuncion);
        lblHoraFuncion.setForeground(new Color(204, 204, 204));
    }

    /**
     * Formatea el nombre del tipo de la sala en las etiquetas
     *
     * @param lblTipoSala etiqueta dónde va el nombre del tipo de sala
     * @param tipoSala el tipo de sala que se pondrá en la etiqueta
     */
    private void configurarTipoSala(JLabel lblTipoSala, String tipoSala) {
        lblTipoSala.setText(tipoSala);
        lblTipoSala.setForeground(new Color(148, 163, 184));
    }

    /**
     * Asocia evento de los clicks sobre el panel de la función electa
     *
     * @param panelFuncion el panel dónde se encuentra la función que escuchará
     * el click
     * @param funcion se envía el DTO de la función para su posterior elección
     * de asientos
     */
    private void configurarEventoClick(JPanel panelFuncion, FuncionDTO funcion) {
        panelFuncion.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                System.out.println("Funcion electa es" + funcion.toString());
            }
        });
    }

    /**
     * Método que inicializa las referencias de dónde se va a mostrar la
     * información de las funciones
     */
    private void inicializarReferencias(){
        etiquetasNombreSala = List.of(
                lblNombreSalaFuncion1, lblNombreSalaFuncion2,
                lblNombreSalaFuncion3, lblNombreSalaFuncion4
        );
        etiquetasHoraFuncion = List.of(
                lblHoraFuncion1, lblHoraFuncion2,
                lblHoraFuncion3, lblHoraFuncion4
        );
        etiquetasTipoSala = List.of(
                lblTipoSalaFuncion1, lblTipoSalaFuncion2,
                lblTipoSalaFuncion3, lblTipoSalaFuncion4
        );
        panelesFunciones = List.of(
                pnlFuncion1, pnlFuncion2,
                pnlFuncion3, pnlFuncion4
        );
    }
    
    /**
     * Método para limpiar las etiquetas dónde irá la información de la película
     * y sus funciones
     *
     * @param lblNombreSala etiqueta dónde va el nombre de la sala de la función
     * @param lblHoraFuncion etiqueta dónde va ala hora de la función
     * @param lblTipoSala etiqueta dónde va el tipo de sala de la función
     */
    private void limpiarEtiquetas(JLabel lblNombreSala, JLabel lblHoraFuncion, JLabel lblTipoSala) {
        lblNombreSala.setText("");
        lblHoraFuncion.setText("");
        lblTipoSala.setText("");
    }
    
    //hardcode
    private List<FuncionDTO> obtenerListaFunciones(){
        return Arrays.asList(
                new FuncionDTO("Sala 1", "12:30", "Sala Tradicional"),
                new FuncionDTO("Sala 2", "09:30", "Sala 3D"),
                new FuncionDTO("Sala 2", "12:00", "Sala Max"),
                new FuncionDTO("Sala 4", "10:25", "Sala Tradicional")
        );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private datechooser.beans.DateChooserCombo datePicker;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblHoraFuncion1;
    private javax.swing.JLabel lblHoraFuncion2;
    private javax.swing.JLabel lblHoraFuncion3;
    private javax.swing.JLabel lblHoraFuncion4;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombreSalaFuncion1;
    private javax.swing.JLabel lblNombreSalaFuncion2;
    private javax.swing.JLabel lblNombreSalaFuncion3;
    private javax.swing.JLabel lblNombreSalaFuncion4;
    private javax.swing.JLabel lblTipoSalaFuncion1;
    private javax.swing.JLabel lblTipoSalaFuncion2;
    private javax.swing.JLabel lblTipoSalaFuncion3;
    private javax.swing.JLabel lblTipoSalaFuncion4;
    private javax.swing.JLabel lblTituloPelicula;
    private presentacion.utilerias.PanelPaginacion panelPaginacion1;
    private javax.swing.JPanel pnlFuncion1;
    private javax.swing.JPanel pnlFuncion2;
    private javax.swing.JPanel pnlFuncion3;
    private javax.swing.JPanel pnlFuncion4;
    private javax.swing.JPanel pnlImagenPelicula;
    // End of variables declaration//GEN-END:variables
}
