/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import presentacion.controles.ControlPantallas;
import dto.AsientoDTO;
import dto.BoletoDTO;
import dto.DetallePrecioDTO;
import dto.FuncionDTO;
import dto.MembresiaDTO;
import dto.ObjetoBeneficioDTO;
import dto.PromocionDTO;
import dto.VentaDTO;
import dto.enums.FormaPago;
import itson.negocios_generadorqr.exceptions.QRGeneradorException;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import presentacion.controles.ControlVentaBoleto;
import presentacion.utilerias.GestorSesion;

/**
 *
 * @author saula
 */

public class PanelInformacionObjetoBeneficio extends javax.swing.JPanel {

    private ObjetoBeneficioDTO objeto;
    private MembresiaDTO membresia;
    
    /**
     * Creates new form PanelInformacionPago
     * @param objeto
     * @param membresia
     */
    public PanelInformacionObjetoBeneficio(ObjetoBeneficioDTO objeto, MembresiaDTO membresia) {
       this.membresia = membresia;
        this.objeto = objeto;
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgDescuentos = new javax.swing.ButtonGroup();
        bgFormaPago = new javax.swing.ButtonGroup();
        pnlInformacionPago = new javax.swing.JPanel();
        lblTituloPelicula = new javax.swing.JLabel();
        lblNombreSala = new javax.swing.JLabel();
        lblFechaFuncion = new javax.swing.JLabel();
        lblHoraFuncion = new javax.swing.JLabel();
        tituloSubtotal = new javax.swing.JLabel();
        lblSubtotalPrecio = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        tituloTotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        tituloSubtotal1 = new javax.swing.JLabel();
        lblSubtotalPrecio1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnConfirmarPago = new javax.swing.JButton();

        setBackground(new java.awt.Color(8, 17, 40));

        pnlInformacionPago.setBackground(new java.awt.Color(18, 26, 60));

        lblTituloPelicula.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        lblTituloPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPelicula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPelicula.setText("NOMBRE BENEFICIO ");

        lblNombreSala.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        lblNombreSala.setForeground(new java.awt.Color(148, 163, 184));

        lblFechaFuncion.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        lblFechaFuncion.setForeground(new java.awt.Color(148, 163, 184));
        lblFechaFuncion.setText("05/09/25");

        lblHoraFuncion.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        lblHoraFuncion.setForeground(new java.awt.Color(148, 163, 184));
        lblHoraFuncion.setText("00:00");

        tituloSubtotal.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tituloSubtotal.setForeground(new java.awt.Color(255, 255, 255));
        tituloSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tituloSubtotal.setText("SALDO:");

        lblSubtotalPrecio.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblSubtotalPrecio.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtotalPrecio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtotalPrecio.setText("P:00.00");

        separador.setBackground(new java.awt.Color(255, 255, 255));

        tituloTotal.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        tituloTotal.setForeground(new java.awt.Color(255, 255, 255));
        tituloTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tituloTotal.setText("TOTAL:");

        lblTotal.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal.setText("$00.00");

        tituloSubtotal1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tituloSubtotal1.setForeground(new java.awt.Color(255, 255, 255));
        tituloSubtotal1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tituloSubtotal1.setText("COSTO:");

        lblSubtotalPrecio1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblSubtotalPrecio1.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtotalPrecio1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubtotalPrecio1.setText("P:00.00");

        javax.swing.GroupLayout pnlInformacionPagoLayout = new javax.swing.GroupLayout(pnlInformacionPago);
        pnlInformacionPago.setLayout(pnlInformacionPagoLayout);
        pnlInformacionPagoLayout.setHorizontalGroup(
            pnlInformacionPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlInformacionPagoLayout.createSequentialGroup()
                .addGroup(pnlInformacionPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformacionPagoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlInformacionPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInformacionPagoLayout.createSequentialGroup()
                                .addComponent(tituloSubtotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSubtotalPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInformacionPagoLayout.createSequentialGroup()
                                .addGroup(pnlInformacionPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNombreSala, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInformacionPagoLayout.createSequentialGroup()
                                        .addComponent(lblFechaFuncion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblHoraFuncion)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlInformacionPagoLayout.createSequentialGroup()
                                .addComponent(tituloSubtotal1)
                                .addGap(12, 12, 12)
                                .addComponent(lblSubtotalPrecio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlInformacionPagoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tituloTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformacionPagoLayout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        pnlInformacionPagoLayout.setVerticalGroup(
            pnlInformacionPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreSala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInformacionPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaFuncion)
                    .addComponent(lblHoraFuncion))
                .addGap(18, 18, 18)
                .addGroup(pnlInformacionPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloSubtotal)
                    .addComponent(lblSubtotalPrecio))
                .addGap(18, 18, 18)
                .addGroup(pnlInformacionPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotalPrecio1)
                    .addComponent(tituloSubtotal1))
                .addGap(88, 88, 88)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInformacionPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloTotal)
                    .addComponent(lblTotal))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        btnVolver.setBackground(new java.awt.Color(37, 99, 235));
        btnVolver.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(26, 51, 83));
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnConfirmarPago.setBackground(new java.awt.Color(37, 99, 235));
        btnConfirmarPago.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnConfirmarPago.setForeground(new java.awt.Color(26, 51, 83));
        btnConfirmarPago.setText("CONFIRMAR PAGO");
        btnConfirmarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253)
                .addComponent(btnConfirmarPago)
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlInformacionPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(pnlInformacionPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ControlPantallas.getInstance().abrirPanelSeleccionBeneficio(pnlInformacionPago, membresia);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnConfirmarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPagoActionPerformed
      
    }//GEN-LAST:event_btnConfirmarPagoActionPerformed

    
    
    
    
   
   
    
    

   
    
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgDescuentos;
    private javax.swing.ButtonGroup bgFormaPago;
    private javax.swing.JButton btnConfirmarPago;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblFechaFuncion;
    private javax.swing.JLabel lblHoraFuncion;
    private javax.swing.JLabel lblNombreSala;
    private javax.swing.JLabel lblSubtotalPrecio;
    private javax.swing.JLabel lblSubtotalPrecio1;
    private javax.swing.JLabel lblTituloPelicula;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlInformacionPago;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel tituloSubtotal;
    private javax.swing.JLabel tituloSubtotal1;
    private javax.swing.JLabel tituloTotal;
    // End of variables declaration//GEN-END:variables
}
