/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author saula
 */
public class PanelInformacionEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form panelInformacionEmpleadoBien
     */
    public PanelInformacionEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnMenuPrincipal = new javax.swing.JButton();
        lblNombreEmpleado = new javax.swing.JLabel();
        lblPuestoEmpleado = new javax.swing.JLabel();
        lblSucursal = new javax.swing.JLabel();
        lblNombreSucursal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 17, 40));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoCine3.png"))); // NOI18N

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenDefault1.png"))); // NOI18N

        lblCerrarSesion.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(148, 163, 184));
        lblCerrarSesion.setText("CERRAR SESIÓN");
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
        });

        lblHora.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblHora.setForeground(new java.awt.Color(241, 245, 249));
        lblHora.setText("00:00");

        lblFecha.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(241, 245, 249));
        lblFecha.setText("05 de septiembre de 2025");

        btnMenuPrincipal.setBackground(new java.awt.Color(37, 99, 235));
        btnMenuPrincipal.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnMenuPrincipal.setText("MENÚ PRINCIPAL");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });

        lblNombreEmpleado.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblNombreEmpleado.setForeground(new java.awt.Color(241, 245, 249));
        lblNombreEmpleado.setText("SAUL APODACA");

        lblPuestoEmpleado.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblPuestoEmpleado.setForeground(new java.awt.Color(241, 245, 249));
        lblPuestoEmpleado.setText("GERENTE");

        lblSucursal.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblSucursal.setForeground(new java.awt.Color(241, 245, 249));
        lblSucursal.setText("SUCURSAL:");

        lblNombreSucursal.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblNombreSucursal.setForeground(new java.awt.Color(241, 245, 249));
        lblNombreSucursal.setText("NAINARI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(lblLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFecha)
                            .addComponent(lblFoto)
                            .addComponent(btnMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(lblHora))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lblCerrarSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblNombreEmpleado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lblSucursal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombreSucursal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lblPuestoEmpleado)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addGap(18, 18, 18)
                .addComponent(lblFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPuestoEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreSucursal)
                    .addComponent(lblSucursal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblFecha)
                .addGap(18, 18, 18)
                .addComponent(lblHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCerrarSesion)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        ControlPantallas.getInstance().abrirMenuPrincipal();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCerrarSesionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreEmpleado;
    private javax.swing.JLabel lblNombreSucursal;
    private javax.swing.JLabel lblPuestoEmpleado;
    private javax.swing.JLabel lblSucursal;
    // End of variables declaration//GEN-END:variables
}
