/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author saula
 */
public class panelOpcionesMenuGerente extends javax.swing.JPanel {

    /**
     * Creates new form panelOpcionesMenu
     */
    public panelOpcionesMenuGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVentaAlimento = new javax.swing.JButton();
        btnGenerarReporte = new javax.swing.JButton();
        btnGestionarPrecios = new javax.swing.JButton();
        btnVentaBoleto = new javax.swing.JButton();
        btnEnviarPromociones = new javax.swing.JButton();
        btnGestionarPeliculas = new javax.swing.JButton();
        btnGestionarPromos = new javax.swing.JButton();
        btnReagendarBoleto = new javax.swing.JButton();
        btnGestionarMembresia = new javax.swing.JButton();
        btnGestionarEmpleados = new javax.swing.JButton();
        btnEscaneoBoleto = new javax.swing.JButton();
        btnReembolsarBoleto = new javax.swing.JButton();
        lblVenderBoleto = new javax.swing.JLabel();
        lblReagendarBoleto = new javax.swing.JLabel();
        lblReembolsarBoleto = new javax.swing.JLabel();
        lblVenderAlimento = new javax.swing.JLabel();
        lblEnviarPromociones = new javax.swing.JLabel();
        lblEscanearBoleto = new javax.swing.JLabel();
        lblGenerarReportes = new javax.swing.JLabel();
        lblGestionarPeliculas = new javax.swing.JLabel();
        lblGestionarMembresias = new javax.swing.JLabel();
        lblGestionarPrecios = new javax.swing.JLabel();
        lblGestionarPromociones = new javax.swing.JLabel();
        lblGestionarEmpleados = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 17, 40));

        btnVentaAlimento.setBackground(new java.awt.Color(18, 31, 55));
        btnVentaAlimento.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnVentaAlimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/venderAlimentos.png"))); // NOI18N
        btnVentaAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaAlimentoActionPerformed(evt);
            }
        });

        btnGenerarReporte.setBackground(new java.awt.Color(18, 31, 55));
        btnGenerarReporte.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnGenerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/generarReportes.png"))); // NOI18N
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        btnGestionarPrecios.setBackground(new java.awt.Color(18, 31, 55));
        btnGestionarPrecios.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnGestionarPrecios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionarPrecios.png"))); // NOI18N
        btnGestionarPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarPreciosActionPerformed(evt);
            }
        });

        btnVentaBoleto.setBackground(new java.awt.Color(18, 31, 55));
        btnVentaBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnVentaBoleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/venderBoleto.png"))); // NOI18N
        btnVentaBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaBoletoActionPerformed(evt);
            }
        });

        btnEnviarPromociones.setBackground(new java.awt.Color(18, 31, 55));
        btnEnviarPromociones.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnEnviarPromociones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/canjearAlimentos.png"))); // NOI18N
        btnEnviarPromociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarPromocionesActionPerformed(evt);
            }
        });

        btnGestionarPeliculas.setBackground(new java.awt.Color(18, 31, 55));
        btnGestionarPeliculas.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnGestionarPeliculas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionarPeliculas.png"))); // NOI18N
        btnGestionarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarPeliculasActionPerformed(evt);
            }
        });

        btnGestionarPromos.setBackground(new java.awt.Color(18, 31, 55));
        btnGestionarPromos.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnGestionarPromos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionarPromos.png"))); // NOI18N
        btnGestionarPromos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarPromosActionPerformed(evt);
            }
        });

        btnReagendarBoleto.setBackground(new java.awt.Color(18, 31, 55));
        btnReagendarBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnReagendarBoleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reagendarBoleto.png"))); // NOI18N
        btnReagendarBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReagendarBoletoActionPerformed(evt);
            }
        });

        btnGestionarMembresia.setBackground(new java.awt.Color(18, 31, 55));
        btnGestionarMembresia.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnGestionarMembresia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionarMembresias.png"))); // NOI18N
        btnGestionarMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarMembresiaActionPerformed(evt);
            }
        });

        btnGestionarEmpleados.setBackground(new java.awt.Color(18, 31, 55));
        btnGestionarEmpleados.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnGestionarEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionarEmpleados.png"))); // NOI18N
        btnGestionarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarEmpleadosActionPerformed(evt);
            }
        });

        btnEscaneoBoleto.setBackground(new java.awt.Color(18, 31, 55));
        btnEscaneoBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnEscaneoBoleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escanearBoleto.png"))); // NOI18N
        btnEscaneoBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscaneoBoletoActionPerformed(evt);
            }
        });

        btnReembolsarBoleto.setBackground(new java.awt.Color(18, 31, 55));
        btnReembolsarBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnReembolsarBoleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ReembolsarBoletos.png"))); // NOI18N
        btnReembolsarBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReembolsarBoletoActionPerformed(evt);
            }
        });

        lblVenderBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblVenderBoleto.setText("VENDER BOLETO");

        lblReagendarBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblReagendarBoleto.setText("REAGENDAR BOLETO");

        lblReembolsarBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblReembolsarBoleto.setText("REEMBOLSAR BOLETO");

        lblVenderAlimento.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblVenderAlimento.setText("VENDER ALIMENTO");

        lblEnviarPromociones.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblEnviarPromociones.setText("ENVIAR PROMOCIONES");

        lblEscanearBoleto.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblEscanearBoleto.setText("ESCANEAR BOLETO");

        lblGenerarReportes.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblGenerarReportes.setText("GENERAR REPORTES");

        lblGestionarPeliculas.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblGestionarPeliculas.setText("GESTIONAR PELICULAS");

        lblGestionarMembresias.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblGestionarMembresias.setText("GESTIONAR MEMBRESÍAS");

        lblGestionarPrecios.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblGestionarPrecios.setText("GESTIONAR PRECIOS");

        lblGestionarPromociones.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblGestionarPromociones.setText("GESTIONAR PROMOCIONES");

        lblGestionarEmpleados.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblGestionarEmpleados.setText("GESTIONAR EMPLEADOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVentaAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVentaBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGestionarPromos, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGestionarPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnviarPromociones, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReagendarBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEscaneoBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReembolsarBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(lblVenderBoleto)
                .addGap(216, 216, 216)
                .addComponent(lblReagendarBoleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblReembolsarBoleto)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblVenderAlimento)
                .addGap(193, 193, 193)
                .addComponent(lblEnviarPromociones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEscanearBoleto)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lblGenerarReportes)
                .addGap(190, 190, 190)
                .addComponent(lblGestionarPeliculas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGestionarMembresias)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lblGestionarPrecios)
                .addGap(168, 168, 168)
                .addComponent(lblGestionarPromociones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGestionarEmpleados)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReembolsarBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblReembolsarBoleto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEscaneoBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVentaBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVenderBoleto)
                        .addGap(18, 18, 18)
                        .addComponent(btnVentaAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReagendarBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblReagendarBoleto)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnviarPromociones, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnviarPromociones)
                    .addComponent(lblVenderAlimento)
                    .addComponent(lblEscanearBoleto))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblGenerarReportes))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGestionarMembresias)
                            .addComponent(lblGestionarPeliculas))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGestionarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarPromos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGestionarPrecios)
                    .addComponent(lblGestionarPromociones)
                    .addComponent(lblGestionarEmpleados))
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentaAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaAlimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentaAlimentoActionPerformed

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void btnGestionarPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPreciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarPreciosActionPerformed

    private void btnVentaBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaBoletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentaBoletoActionPerformed

    private void btnEnviarPromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarPromocionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarPromocionesActionPerformed

    private void btnGestionarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPeliculasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarPeliculasActionPerformed

    private void btnGestionarPromosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPromosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarPromosActionPerformed

    private void btnReagendarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReagendarBoletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReagendarBoletoActionPerformed

    private void btnGestionarMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarMembresiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarMembresiaActionPerformed

    private void btnGestionarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarEmpleadosActionPerformed

    private void btnEscaneoBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscaneoBoletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEscaneoBoletoActionPerformed

    private void btnReembolsarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReembolsarBoletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReembolsarBoletoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarPromociones;
    private javax.swing.JButton btnEscaneoBoleto;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnGestionarEmpleados;
    private javax.swing.JButton btnGestionarMembresia;
    private javax.swing.JButton btnGestionarPeliculas;
    private javax.swing.JButton btnGestionarPrecios;
    private javax.swing.JButton btnGestionarPromos;
    private javax.swing.JButton btnReagendarBoleto;
    private javax.swing.JButton btnReembolsarBoleto;
    private javax.swing.JButton btnVentaAlimento;
    private javax.swing.JButton btnVentaBoleto;
    private javax.swing.JLabel lblEnviarPromociones;
    private javax.swing.JLabel lblEscanearBoleto;
    private javax.swing.JLabel lblGenerarReportes;
    private javax.swing.JLabel lblGestionarEmpleados;
    private javax.swing.JLabel lblGestionarMembresias;
    private javax.swing.JLabel lblGestionarPeliculas;
    private javax.swing.JLabel lblGestionarPrecios;
    private javax.swing.JLabel lblGestionarPromociones;
    private javax.swing.JLabel lblReagendarBoleto;
    private javax.swing.JLabel lblReembolsarBoleto;
    private javax.swing.JLabel lblVenderAlimento;
    private javax.swing.JLabel lblVenderBoleto;
    // End of variables declaration//GEN-END:variables
}
